var basic=[];

basic.push({ eng:"accept",tr:" kabul etmek "});
basic.push({ eng:"agree",tr:" aynı fikirde olmak "});
basic.push({ eng:"allow",tr:" izin vermek "});
basic.push({ eng:"answer",tr:" cevap vermek "});
basic.push({ eng:"arrive",tr:" varmak "});
basic.push({ eng:"ask",tr:" soru sormak "});
basic.push({ eng:"borrow",tr:" ödünç almak "});
basic.push({ eng:"call",tr:" telefonla aramak "});
basic.push({ eng:"carry",tr:" taşımak "});
basic.push({ eng:"change",tr:" değiştirmek "});
basic.push({ eng:"clean",tr:" temizlemek "});
basic.push({ eng:"close",tr:" kapatmak "});
basic.push({ eng:"help",tr:" yardım etmek "});
basic.push({ eng:"invent",tr:" icat etmek "});
basic.push({ eng:"invite",tr:" davet etmek "});
basic.push({ eng:"kill",tr:" öldürmek "});
basic.push({ eng:"kiss",tr:" öpmek "});
basic.push({ eng:"lick",tr:" yalamak "});
basic.push({ eng:"lie",tr:" yalan söylemek "});
basic.push({ eng:"live",tr:" yaşamak "});
basic.push({ eng:"look",tr:" bakmak "});
basic.push({ eng:"love",tr:" sevmek "});
basic.push({ eng:"like",tr:" hoşlanmak "});
basic.push({ eng:"marry",tr:" evlenmek "});
basic.push({ eng:"need",tr:" ihtiyacı olmak "});
basic.push({ eng:"offer",tr:" teklif etmek "});
basic.push({ eng:"paint",tr:" boyamak "});
basic.push({ eng:"play",tr:" oynamak "});
basic.push({ eng:"prefer",tr:" tercih etmek "});
basic.push({ eng:"remember",tr:" hatırlamak "});
basic.push({ eng:"return",tr:" geri dönmek "});
basic.push({ eng:"smell",tr:" koklamak "});
basic.push({ eng:"smile",tr:" gülümsemek "});
basic.push({ eng:"smoke",tr:" sigara içmek "});
basic.push({ eng:"talk",tr:" konuşmak "});
basic.push({ eng:"touch",tr:" dokunmak "});
basic.push({ eng:"train",tr:" eğitmek "});
basic.push({ eng:"use",tr:" kullanmak "});
basic.push({ eng:"waste",tr:" ziyan etmek "});
basic.push({ eng:"wash",tr:" yıkamak "});
basic.push({ eng:"whisper",tr:" fısıldamak "});
basic.push({ eng:"hit",tr:" vurmak "});
basic.push({ eng:"begin",tr:" başlamak "});
basic.push({ eng:"bite",tr:" ısırmak "});
basic.push({ eng:"blow",tr:" üflemek "});
basic.push({ eng:"break",tr:" kırmak "});
basic.push({ eng:"bring",tr:" getirmek "});
basic.push({ eng:"buy",tr:" satın almak "});
basic.push({ eng:"catch",tr:" yakalamak "});
basic.push({ eng:"choose",tr:" seçmek "});
basic.push({ eng:"come",tr:" gelmek "});
basic.push({ eng:"cut",tr:" kesmek "});
basic.push({ eng:"die",tr:" ölmek "});
basic.push({ eng:"draw",tr:" çizmek "});
basic.push({ eng:"dream",tr:" rüya görmek "});
basic.push({ eng:"drink",tr:" içmek "});
basic.push({ eng:"drive",tr:" araba sürmek "});
basic.push({ eng:"eat",tr:" yemek "});
basic.push({ eng:"fall",tr:" düşmek "});
basic.push({ eng:"feel",tr:" hissetmek "});
basic.push({ eng:"find",tr:" bulmak "});
basic.push({ eng:"forget",tr:" unutmak "});
basic.push({ eng:"get",tr:" elde etmek "});
basic.push({ eng:"give",tr:" vermek "});
basic.push({ eng:"go",tr:" gitmek "});
basic.push({ eng:"grow",tr:" yetiştirmek "});
basic.push({ eng:"have",tr:" sahip olmak "});
basic.push({ eng:"hear",tr:" duymak "});
basic.push({ eng:"hide",tr:" saklamak "});
basic.push({ eng:"know",tr:" bilmek "});
basic.push({ eng:"learn",tr:" öğrenmek "});
basic.push({ eng:"leave",tr:" ayrılmak "});
basic.push({ eng:"make",tr:" yapmak "});
basic.push({ eng:"pay",tr:" ödemek "});
basic.push({ eng:"put",tr:" koymak "});
basic.push({ eng:"read",tr:" okumak "});
basic.push({ eng:"rise",tr:" yükselmek "});
basic.push({ eng:"ring",tr:" çalmak "});
basic.push({ eng:"run",tr:" koşmak "});
basic.push({ eng:"say",tr:" söylemek "});
basic.push({ eng:"see",tr:" görmek "});
basic.push({ eng:"sell",tr:" satmak "});
basic.push({ eng:"send",tr:" göndermek "});
basic.push({ eng:"shake",tr:" titremek "});
basic.push({ eng:"shine",tr:" parlamak "});
basic.push({ eng:"show",tr:" göstermek "});
basic.push({ eng:"sing",tr:" şarkı söylemek "});
basic.push({ eng:"sleep",tr:" uyumak "});
basic.push({ eng:"spend",tr:" harcamak "});
basic.push({ eng:"swim",tr:" yüzmek "});
basic.push({ eng:"take",tr:" almak "});
basic.push({ eng:"tear",tr:" yırtmak "});
basic.push({ eng:"tell",tr:" söylemek "});
basic.push({ eng:"think",tr:" düşünmek "});
basic.push({ eng:"understand",tr:" anlamak "});
basic.push({ eng:"wake",tr:" uyanmak "});
basic.push({ eng:"wear",tr:" giymek "});
basic.push({ eng:"win",tr:" kanmak "});
basic.push({ eng:"wipe",tr:" silmek "});
basic.push({ eng:"weep",tr:" ağlamak "});


var medium = [];

medium.push({ eng:"Accept",tr:"kabul etmek"});
medium.push({ eng:"Add",tr:"eklemek"});
medium.push({ eng:"Admire",tr:"hayran olmak"});
medium.push({ eng:"Admit",tr:"itiraf etmek"});
medium.push({ eng:"Advise",tr:"tavsiye etmek"});
medium.push({ eng:"Afford",tr:"karşılamak"});
medium.push({ eng:"Agree",tr:"aynı fikirde olmak"});
medium.push({ eng:"Allow",tr:"izin vermek"});
medium.push({ eng:"Amuse",tr:"eğlendirmek"});
medium.push({ eng:"Announce",tr:"duyurmak"});
medium.push({ eng:"Annoy",tr:"rahatsız etmek"});
medium.push({ eng:"Answer",tr:"cevap vermek"});
medium.push({ eng:"Apologise",tr:"özür dilemek"});
medium.push({ eng:"Appear",tr:"gözükmek"});
medium.push({ eng:"Applaud",tr:"alkışlamak"});
medium.push({ eng:"Appreciate",tr:"memnun olmak"});
medium.push({ eng:"Approve",tr:"onaylamak"});
medium.push({ eng:"Argue",tr:"tartışmak"});
medium.push({ eng:"Arrange",tr:"düzenlemek"});
medium.push({ eng:"Arrest",tr:"tutuklamak"});
medium.push({ eng:"Arrive",tr:"varmak"});
medium.push({ eng:"Ask",tr:"sormak"});
medium.push({ eng:"Attach",tr:"iliştirmek"});
medium.push({ eng:"Attack",tr:"saldırmak"});
medium.push({ eng:"Attempt",tr:"girişimde bulunmak"});
medium.push({ eng:"Attend",tr:"katılmak"});
medium.push({ eng:"Attract",tr:"çekmek"});
medium.push({ eng:"Avoid",tr:"sakınmak"});
medium.push({ eng:"Back",tr:"geriye gitmek"});
medium.push({ eng:"Bake",tr:"pişirmek"});
medium.push({ eng:"Balance",tr:"dengelemek"});
medium.push({ eng:"Ban",tr:"yasaklamak"});
medium.push({ eng:"Bang",tr:"vurmak/çarpmak"});
medium.push({ eng:"Bat",tr:"sopayla vurmak"});
medium.push({ eng:"Bathe",tr:"banyo yapmak"});
medium.push({ eng:"Battle",tr:"savaşmak"});
medium.push({ eng:"Beg",tr:"özür dilemek"});
medium.push({ eng:"Behave",tr:"davranmak"});
medium.push({ eng:"Belong",tr:"ait olmak"});
medium.push({ eng:"Bless",tr:"kutsamak"});
medium.push({ eng:"Blind",tr:"körleştirmek"});
medium.push({ eng:"Blink",tr:"göz kırpmak"});
medium.push({ eng:"Blush",tr:"utançtan kızarmak"});
medium.push({ eng:"Boast",tr:"böbürlenmek"});
medium.push({ eng:"Boil",tr:"kaynamak"});
medium.push({ eng:"Bolt",tr:"irkilmek"});
medium.push({ eng:"Bomb",tr:"bombalamak"});
medium.push({ eng:"Book",tr:"rezervasyon yapmak"});
medium.push({ eng:"Bore",tr:"canını sıkmak"});
medium.push({ eng:"Borrow",tr:"ödünç almak"});
medium.push({ eng:"Bounce",tr:"zıplamak"});
medium.push({ eng:"Bow",tr:"reverans yapmak"});
medium.push({ eng:"Box",tr:"yumruklaşmak"});
medium.push({ eng:"Brake",tr:"fren yapmak"});
medium.push({ eng:"Branch",tr:"dallanmak"});
medium.push({ eng:"Breathe",tr:"nefes almak"});
medium.push({ eng:"Bruise",tr:"çürütmek"});
medium.push({ eng:"Brush",tr:"fırçalamak"});
medium.push({ eng:"Burn",tr:"yanmak"});
medium.push({ eng:"Bury",tr:"gömmek"});
medium.push({ eng:"Buzz",tr:"vızıldamak"});
medium.push({ eng:"Calculate",tr:"hesaplamak"});
medium.push({ eng:"Call",tr:"aramak"});
medium.push({ eng:"Camp",tr:"kamp yapmak"});
medium.push({ eng:"Care",tr:"önemsemek"});
medium.push({ eng:"Carry",tr:"taşımak"});
medium.push({ eng:"Carve",tr:"oymak"});
medium.push({ eng:"Cause",tr:"neden olmak"});
medium.push({ eng:"Challenge",tr:"meydan okumak"});
medium.push({ eng:"Change",tr:"değiştirmek"});
medium.push({ eng:"Charge",tr:"şarj etmek"});
medium.push({ eng:"Chase",tr:"kovalamak"});
medium.push({ eng:"Cheat",tr:"aldatmak"});
medium.push({ eng:"Check",tr:"kontrol etmek"});
medium.push({ eng:"Cheer",tr:"tezahürat yapmak"});
medium.push({ eng:"Chew",tr:"çiğnemek"});
medium.push({ eng:"Chop",tr:"doğramak"});
medium.push({ eng:"Claim",tr:"iddia etmek"});
medium.push({ eng:"Clap",tr:"alkışlamak"});
medium.push({ eng:"Clean",tr:"temizlemek"});
medium.push({ eng:"Clear",tr:"temizlemek"});
medium.push({ eng:"Clip",tr:"tutturmak"});
medium.push({ eng:"Close",tr:"kapatmak"});
medium.push({ eng:"Coach",tr:"yetiştirmek/çalıştırmak"});
medium.push({ eng:"Collect",tr:"biriktirmek"});
medium.push({ eng:"Colour",tr:"renklendirmek"});
medium.push({ eng:"Comb",tr:"taramak"});
medium.push({ eng:"Command",tr:"emir vermek"});
medium.push({ eng:"Communicate",tr:"iletişim kurmak"});
medium.push({ eng:"Compare",tr:"karşılaştırmak"});
medium.push({ eng:"Compete",tr:"yarışmak"});
medium.push({ eng:"Complain",tr:"yakınmak"});
medium.push({ eng:"Complete",tr:"tamamlamak"});
medium.push({ eng:"Concentrate",tr:"konsantre olmak"});
medium.push({ eng:"Concern",tr:"kaygılandırmak"});
medium.push({ eng:"Confess",tr:"itiraf etmek"});
medium.push({ eng:"Confuse",tr:"kafasını karıştırmak"});
medium.push({ eng:"Connect",tr:"bağlamak"});
medium.push({ eng:"Consider",tr:"hesaba katmak"});
medium.push({ eng:"Consist",tr:"-den oluşmak"});
medium.push({ eng:"Contain",tr:"içermek"});
medium.push({ eng:"Continue",tr:"devam etmek"});
medium.push({ eng:"Copy",tr:"kopyalamak"});
medium.push({ eng:"Correct",tr:"düzeltmek"});
medium.push({ eng:"Cough",tr:"öksürmek"});
medium.push({ eng:"Count",tr:"saymak"});
medium.push({ eng:"Cover",tr:"örtmek"});
medium.push({ eng:"Crack",tr:"çatlamak/çatlatmak"});
medium.push({ eng:"Crash",tr:"gürültüyle çarpma"});
medium.push({ eng:"Crawl",tr:"emeklemek"});
medium.push({ eng:"Cross",tr:"öbür tarafa geçmek"});
medium.push({ eng:"Crush",tr:"ezmek"});
medium.push({ eng:"Cry",tr:"ağlamak"});
medium.push({ eng:"Cure",tr:"tedavi etmek"});
medium.push({ eng:"Cycle",tr:"bisiklet sürmek"});
medium.push({ eng:"Damage",tr:"hasar vermek"});
medium.push({ eng:"Dance",tr:"dansetmek"});
medium.push({ eng:"Dare",tr:"cüret etmek"});
medium.push({ eng:"Deceive",tr:"aldatmak"});
medium.push({ eng:"Decide",tr:"karar vermek"});
medium.push({ eng:"Decorate",tr:"dekore etmek"});
medium.push({ eng:"Delay",tr:"gecikmek/geciktirmek"});
medium.push({ eng:"Delight",tr:"zevk vermek"});
medium.push({ eng:"Deliver",tr:"teslim etmek"});
medium.push({ eng:"Depend",tr:"bağlı olmak"});
medium.push({ eng:"Describe",tr:"tanımlamak"});
medium.push({ eng:"Desert",tr:"terketmek"});
medium.push({ eng:"Deserve",tr:"layık olmak"});
medium.push({ eng:"Destroy",tr:"mahvetmek"});
medium.push({ eng:"Detect",tr:"tespit etmek"});
medium.push({ eng:"Develop",tr:"geliştirmek"});
medium.push({ eng:"Disagree",tr:"aynı fikirde olmamak"});
medium.push({ eng:"Disappear",tr:"gözden kaybolmak"});
medium.push({ eng:"Disapprove",tr:"tasvip etmemek"});
medium.push({ eng:"Discover",tr:"keşfetmek"});
medium.push({ eng:"Dislike",tr:"hoşlanmamak"});
medium.push({ eng:"Divide",tr:"bölmek"});
medium.push({ eng:"Double",tr:"iki misli yapmak"});
medium.push({ eng:"Doubt",tr:"-den kuşkulanmak"});
medium.push({ eng:"Drag",tr:"sürüklemek"});
medium.push({ eng:"Drain",tr:"akıtmak/akmak"});
medium.push({ eng:"Dream",tr:"rüya görmek/hayal kurmak"});
medium.push({ eng:"Dress",tr:"giyinmek"});
medium.push({ eng:"Drip",tr:"damlamak"});
medium.push({ eng:"Drop",tr:"düşürmek"});
medium.push({ eng:"Drown",tr:"boğulmak"});
medium.push({ eng:"Drum",tr:"davul çalmak"});
medium.push({ eng:"Dry",tr:"kurumak/kurutmak"});
medium.push({ eng:"Dust",tr:"tozunu almak"});
medium.push({ eng:"Earn",tr:"kazanmak"});
medium.push({ eng:"Educate",tr:"eğitmek"});
medium.push({ eng:"Embarrass",tr:"utandırmak"});
medium.push({ eng:"Employ",tr:"iş vermek"});
medium.push({ eng:"Empty",tr:"boşaltmak"});
medium.push({ eng:"Encourage",tr:"cesaretlendirmek"});
medium.push({ eng:"End",tr:"bitirmek"});
medium.push({ eng:"Enjoy",tr:"zevk almak"});
medium.push({ eng:"Enter",tr:"girmek"});
medium.push({ eng:"Entertain",tr:"eğlendirmek"});
medium.push({ eng:"Escape",tr:"kaçmak"});
medium.push({ eng:"Examine",tr:"muayene etmek"});
medium.push({ eng:"Excite",tr:"heyecanlandırmak"});
medium.push({ eng:"Excuse",tr:"bağışlamak"});
medium.push({ eng:"Exercise",tr:"egzersiz yapmak"});
medium.push({ eng:"Exist",tr:"var olmak"});
medium.push({ eng:"Expand",tr:"genişletmek"});
medium.push({ eng:"Expect",tr:"ummak/beklemek"});
medium.push({ eng:"Explain",tr:"açıklamak"});
medium.push({ eng:"Explode",tr:"patlamak"});
medium.push({ eng:"Extend",tr:"erişmek/yayılmak"});
medium.push({ eng:"Face",tr:"yüzleşmek"});
medium.push({ eng:"Fade",tr:"solmak"});
medium.push({ eng:"Fail",tr:"başarısız olmak"});
medium.push({ eng:"Fasten",tr:"bağlamak/tutturmak"});
medium.push({ eng:"Fax",tr:"faks çekmek"});
medium.push({ eng:"Fear",tr:"korkmak"});
medium.push({ eng:"Fence",tr:"çitle çevirmek"});
medium.push({ eng:"File",tr:"dosyalamak"});
medium.push({ eng:"Fill",tr:"doldurmak"});
medium.push({ eng:"Film",tr:"film çekmek"});
medium.push({ eng:"Fire",tr:"tutuşturmak/ateş etmek"});
medium.push({ eng:"Fit",tr:"(giysi) uymak"});
medium.push({ eng:"Fix",tr:"sabitlemek/belirlemek"});
medium.push({ eng:"Flash",tr:"birden parlamak"});
medium.push({ eng:"Float",tr:"batmadan yüzmek"});
medium.push({ eng:"Flood",tr:"su basmak"});
medium.push({ eng:"Flow",tr:"akmak"});
medium.push({ eng:"Flower",tr:"çiçek açmak"});
medium.push({ eng:"Follow",tr:"takip etmek"});
medium.push({ eng:"Fool",tr:"kandırmak"});
medium.push({ eng:"Force",tr:"zorlamak"});
medium.push({ eng:"Form",tr:"biçimlendirmek"});
medium.push({ eng:"Found",tr:"inşa etmek"});
medium.push({ eng:"Frame",tr:"çerçevelemek"});
medium.push({ eng:"Frighten",tr:"korkutmak"});
medium.push({ eng:"Fry",tr:"kızartmak"});
medium.push({ eng:"Glow",tr:"ışık vermek"});
medium.push({ eng:"Glue",tr:"yapıştırmak"});
medium.push({ eng:"Grab",tr:"kavramak"});
medium.push({ eng:"Grate",tr:"rendelemek"});
medium.push({ eng:"Grease",tr:"yağlamak"});
medium.push({ eng:"Greet",tr:"selamlamak/karşılamak"});
medium.push({ eng:"Grip",tr:"sımsıkı tutmak"});
medium.push({ eng:"Groan",tr:"inlemek"});
medium.push({ eng:"Guarantee",tr:"garanti vermek"});
medium.push({ eng:"Guard",tr:"korumak"});
medium.push({ eng:"Guess",tr:"tahmin etmek"});
medium.push({ eng:"Guide",tr:"kılavuzluk etmek"});
medium.push({ eng:"Hammer",tr:"çekiçle vurmak"});
medium.push({ eng:"Hand",tr:"uzatmak"});
medium.push({ eng:"Handle",tr:"başa çıkmak/yönetmek"});
medium.push({ eng:"Hang",tr:"asmak"});
medium.push({ eng:"Happen",tr:"olmak"});
medium.push({ eng:"Harm",tr:"zarar vermek"});
medium.push({ eng:"Hate",tr:"efret etmek"});
medium.push({ eng:"Haunt",tr:"(cin",tr:"peri) uğramak"});
medium.push({ eng:"Head",tr:"başı çekmek"});
medium.push({ eng:"Heal",tr:"iyileşmek"});
medium.push({ eng:"Heat",tr:"ısıtmak"});
medium.push({ eng:"Help",tr:"yardım etmek"});
medium.push({ eng:"Hop",tr:"hoplamak"});
medium.push({ eng:"Hope",tr:"ümit etmek"});
medium.push({ eng:"Hug",tr:"kucaklamak"});
medium.push({ eng:"Hunt",tr:"avlanmak"});
medium.push({ eng:"Hurry",tr:"acele etmek"});
medium.push({ eng:"Identify",tr:"teşhis etmek"});
medium.push({ eng:"Imagine",tr:"hayal etmek"});
medium.push({ eng:"Impress",tr:"etkilemek"});
medium.push({ eng:"Improve",tr:"geliştirmek"});
medium.push({ eng:"Include",tr:"içermek"});
medium.push({ eng:"Increase",tr:"artmak"});
medium.push({ eng:"Influence",tr:"etkilemek"});
medium.push({ eng:"Inform",tr:"bilgilendirmek"});
medium.push({ eng:"Inject",tr:"iğne yapmak"});
medium.push({ eng:"Injure",tr:"incitmek/yaralamak"});
medium.push({ eng:"Instruct",tr:"talimat vermek"});
medium.push({ eng:"Intend",tr:"niyet etmek"});
medium.push({ eng:"Interest",tr:"ilgi uyandırmak"});
medium.push({ eng:"Introduce",tr:"tanıştırmak"});
medium.push({ eng:"Invent",tr:"bulmak/keşfetmek"});
medium.push({ eng:"Invite",tr:"davet etmek"});
medium.push({ eng:"Itch",tr:"kaşımak"});
medium.push({ eng:"Jail",tr:"hapsetmek"});
medium.push({ eng:"Jam",tr:"sıkıştırmak/tıkamak"});
medium.push({ eng:"Join",tr:"katılmak"});
medium.push({ eng:"Joke",tr:"şaka yapmak"});
medium.push({ eng:"Judge",tr:"yargılamak"});
medium.push({ eng:"Jump",tr:"zıplamak"});
medium.push({ eng:"Kick",tr:"tekmelemek"});
medium.push({ eng:"Kill",tr:"öldürmek"});
medium.push({ eng:"Kiss",tr:"öpmek"});
medium.push({ eng:"Kneel",tr:"diz çökmek"});
medium.push({ eng:"Knit",tr:"örmek"});
medium.push({ eng:"Knock",tr:"vurmak"});
medium.push({ eng:"Label",tr:"etiketlemek"});
medium.push({ eng:"Land",tr:"iniş yapmak"});
medium.push({ eng:"Last",tr:"sürmek"});
medium.push({ eng:"Laugh",tr:"gülmek"});
medium.push({ eng:"Launch",tr:"(roket) fırlatmak"});
medium.push({ eng:"Learn",tr:"öğrenmek"});
medium.push({ eng:"Level",tr:"düzleştirmek"});
medium.push({ eng:"License",tr:"ruhsat vermek"});
medium.push({ eng:"Lick",tr:"yalamak"});
medium.push({ eng:"Lie",tr:"yalan söylemek"});
medium.push({ eng:"Lighten",tr:"aydınlatmak"});
medium.push({ eng:"Like",tr:"hoşlanmak"});
medium.push({ eng:"List",tr:"listelemek"});
medium.push({ eng:"Listen",tr:"dinlemek"});
medium.push({ eng:"Live",tr:"yaşamak"});
medium.push({ eng:"Load",tr:"yüklemek"});
medium.push({ eng:"Lock",tr:"kilitlemek"});
medium.push({ eng:""});
medium.push({ eng:""});
medium.push({ eng:"Look",tr:"bakmak"});
medium.push({ eng:"Love",tr:"sevmek"});
medium.push({ eng:"Man",tr:"adam vermek"});
medium.push({ eng:"Manage",tr:"yönetmek"});
medium.push({ eng:"March",tr:"uygun adım yürümek"});
medium.push({ eng:"Mark",tr:"işaretlemek"});
medium.push({ eng:"Marry",tr:"evlenmek"});
medium.push({ eng:"Match",tr:"eşleştirmek"});
medium.push({ eng:"Mate",tr:"çiftleşmek"});
medium.push({ eng:"Matter",tr:"önemli olmak"});
medium.push({ eng:"Measure",tr:"ölçmek"});
medium.push({ eng:"Melt",tr:"erimek"});
medium.push({ eng:"Memorise",tr:"ezberlemek"});
medium.push({ eng:"Mend",tr:"tamir etmek"});
medium.push({ eng:"mess up",tr:"dağıtmak"});
medium.push({ eng:"milk",tr:"süt sağmak"});
medium.push({ eng:"mine",tr:"maden işletmek"});
medium.push({ eng:"miss",tr:"özlemek/kaçırmak"});
medium.push({ eng:"mix",tr:"karıştırmak"});
medium.push({ eng:"move",tr:"taşınmak"});
medium.push({ eng:"muddle",tr:"karıştırmak"});
medium.push({ eng:"mug",tr:"saldırıp soymak"});
medium.push({ eng:"multiply",tr:"çoğalmak"});
medium.push({ eng:"murder",tr:"cinayet işlemek"});
medium.push({ eng:"nail",tr:"çivilemek"});
medium.push({ eng:"name",tr:"ad vermek"});
medium.push({ eng:"need",tr:"ihtiyaç duymak"});
medium.push({ eng:"nest",tr:"yuva yapmak"});
medium.push({ eng:"nod",tr:"başını sallamak"});
medium.push({ eng:"note",tr:"not etmek"});
medium.push({ eng:"notice",tr:"farkına varmak"});
medium.push({ eng:"number",tr:"numaralamak"});
medium.push({ eng:"obey",tr:"itaat etmek"});
medium.push({ eng:"object",tr:"itiraz etmek"});
medium.push({ eng:"observe",tr:"incelemek"});
medium.push({ eng:"obtain",tr:"elde etmek"});
medium.push({ eng:"occur",tr:"meydana gelmek"});
medium.push({ eng:"offend",tr:"gücendirmek"});
medium.push({ eng:"offer",tr:"teklif etmek"});
medium.push({ eng:"open",tr:"açmak"});
medium.push({ eng:"order",tr:"ısmarlamak"});
medium.push({ eng:"owe",tr:"borcu olmak"});
medium.push({ eng:"own",tr:"sahip olmak"});
medium.push({ eng:"pack",tr:"paket yapmak"});
medium.push({ eng:"paint",tr:"boyamak"});
medium.push({ eng:"park",tr:"park etmek"});
medium.push({ eng:"pass",tr:"geçmek"});
medium.push({ eng:"paste",tr:"yapıştırmak"});
medium.push({ eng:"pat",tr:"hafifçe vurmak"});
medium.push({ eng:"pause",tr:"duraklamak"});
medium.push({ eng:"peel",tr:"kabuğunu soymak"});
medium.push({ eng:"perform",tr:"temsil etmek"});
medium.push({ eng:"permit",tr:"izin vermek"});
medium.push({ eng:"phone",tr:"telefon açmak"});
medium.push({ eng:"pick",tr:"seçmek/ayırmak"});
medium.push({ eng:"pinch",tr:"çimdiklemek"});
medium.push({ eng:"pine",tr:"güçten düşmek"});
medium.push({ eng:"place",tr:"yerleştirmek"});
medium.push({ eng:"plan",tr:"planlamak"});
medium.push({ eng:"plant",tr:"yerleştirmek/ekmek"});
medium.push({ eng:"play",tr:"oynamak"});
medium.push({ eng:"please",tr:"memnun etmek"});
medium.push({ eng:"point",tr:"işaret etmek"});
medium.push({ eng:"polish",tr:"parlatmak/cilalamak"});
medium.push({ eng:"possess",tr:"sahip olmak"});
medium.push({ eng:"post",tr:"postalamak"});
medium.push({ eng:"pour",tr:"doldurmak"});
medium.push({ eng:"practise",tr:"pratik yapmak"});
medium.push({ eng:"pray",tr:"dua etmek"});
medium.push({ eng:"prefer",tr:"tercih etmek"});
medium.push({ eng:"prepare",tr:"hazırlamak"});
medium.push({ eng:"present",tr:"takdim etmek/sunmak"});
medium.push({ eng:"preserve",tr:"korumak/saklamak"});
medium.push({ eng:"press",tr:"sıkıştırmak"});
medium.push({ eng:"prevent",tr:"önlemek"});
medium.push({ eng:"print",tr:"basmak"});
medium.push({ eng:"produce",tr:"üretmek"});
medium.push({ eng:"program",tr:"programlamak"});
medium.push({ eng:"promise",tr:"söz vermek"});
medium.push({ eng:"protect",tr:"korumak"});
medium.push({ eng:"provide",tr:"sağlamak"});
medium.push({ eng:"pull",tr:"çekmek"});
medium.push({ eng:"pump",tr:"pompalamak"});
medium.push({ eng:"punch",tr:"yumruk atmak"});
medium.push({ eng:"punish",tr:"cezalandırmak"});
medium.push({ eng:"push",tr:"itmek"});
medium.push({ eng:"question",tr:"soru sormak"});
medium.push({ eng:"queue",tr:"kuyruğa girmek"});
medium.push({ eng:"race",tr:"yarışmak"});
medium.push({ eng:"rain",tr:"yağmur yağmak"});
medium.push({ eng:"raise",tr:"kaldırmak"});
medium.push({ eng:"reach",tr:"ulaşmak"});
medium.push({ eng:"realise",tr:"farkına varmak"});
medium.push({ eng:"receive",tr:"teslim almak"});
medium.push({ eng:"recognise",tr:"tanımak/takdir etmek"});
medium.push({ eng:"record",tr:"kaydetmek"});
medium.push({ eng:"reduce",tr:"azaltmak/indirmek"});
medium.push({ eng:"reflect",tr:"yansıtmak"});
medium.push({ eng:"refuse",tr:"reddetmek"});
medium.push({ eng:"regret",tr:"ihmal etmek"});
medium.push({ eng:"reject",tr:"reddetmek/atmak"});
medium.push({ eng:"relax",tr:"rahatlamak"});
medium.push({ eng:"release",tr:"serbest bırakmak"});
medium.push({ eng:"rely",tr:"itimat etmek"});
medium.push({ eng:"remain",tr:"kalmak"});
medium.push({ eng:"remember",tr:"hatırlamak"});
medium.push({ eng:"remind",tr:"hatırlatmak"});
medium.push({ eng:"remove",tr:"çıkarmak/temizlemek"});
medium.push({ eng:"repair",tr:"tamir etmek"});
medium.push({ eng:"repeat",tr:"tamir etmek"});
medium.push({ eng:"replace",tr:"eski yerine koymak"});
medium.push({ eng:"reply",tr:"karşılık vermek"});
medium.push({ eng:"report",tr:"haber vermek"});
medium.push({ eng:"reproduce",tr:"üretmek"});
medium.push({ eng:"request",tr:"rica etmek"});
medium.push({ eng:"rescue",tr:"kurtarmak"});
medium.push({ eng:"retire",tr:"emekli olmak"});
medium.push({ eng:"return",tr:"dönmek/geri vermek"});
medium.push({ eng:"risk",tr:"risk almak"});
medium.push({ eng:"rock",tr:"sallamak"});
medium.push({ eng:"roll",tr:"yuvarlamak"});
medium.push({ eng:"ruin",tr:"harab etmek"});
medium.push({ eng:"rule",tr:"hükmetmek"});
medium.push({ eng:"rush",tr:"acele etmek"});
medium.push({ eng:"sail",tr:"yelken açmak"});
medium.push({ eng:"satisfy",tr:"hoşnut etmek"});
medium.push({ eng:"save",tr:"kurtarmak"});
medium.push({ eng:"saw",tr:"testere ile kesmek"});
medium.push({ eng:"scare",tr:"korkutmak"});
medium.push({ eng:"scratch",tr:"tırmalamak"});
medium.push({ eng:"scream",tr:"çığlık atmak"});
medium.push({ eng:"screw",tr:"vidalamak"});
medium.push({ eng:"scribble",tr:"çiziktirmek"});
medium.push({ eng:"scrub",tr:"fırçalamak/ovalamak"});
medium.push({ eng:"seal",tr:"mühürlemek"});
medium.push({ eng:"search",tr:"araştırmak"});
medium.push({ eng:"separate",tr:"ayırmak"});
medium.push({ eng:"serve",tr:"hizmet etmek"});
medium.push({ eng:"settle",tr:"yerleşmek"});
medium.push({ eng:"shade",tr:"gölgelemek"});
medium.push({ eng:"share",tr:"paylaşmak"});
medium.push({ eng:"shave",tr:"traş olmak"});
medium.push({ eng:"shelter",tr:"barındırmak"});
medium.push({ eng:"shock",tr:"şok etmek"});
medium.push({ eng:"shop",tr:"alışveriş yapmak"});
medium.push({ eng:"shrug",tr:"omuz silkmek"});
medium.push({ eng:"sigh",tr:"iç çekmek"});
medium.push({ eng:"sign",tr:"imzalamak"});
medium.push({ eng:"signal",tr:"işaret vermek"});
medium.push({ eng:"sin",tr:"günah işlemek"});
medium.push({ eng:"ski",tr:"kayak yapmak"});
medium.push({ eng:"skip",tr:"zıplamak/sekmek"});
medium.push({ eng:"slap",tr:"tokatlamak"});
medium.push({ eng:"slip",tr:"kaymak"});
medium.push({ eng:"slow",tr:"yavaşlamak"});
medium.push({ eng:"smell",tr:"koklamak"});
medium.push({ eng:"smile",tr:"gülümsemek"});
medium.push({ eng:"smoke",tr:"sigara içmek"});
medium.push({ eng:"sneeze",tr:"aksırmak"});
medium.push({ eng:"sniff",tr:"burnunu çekmek/koklamak"});
medium.push({ eng:"snore",tr:"horlamak"});
medium.push({ eng:"snow",tr:"kar yağmak"});
medium.push({ eng:"sound",tr:"ses çıkarmak"});
medium.push({ eng:"spare",tr:"esirgemek"});
medium.push({ eng:"spell",tr:"hecelemek"});
medium.push({ eng:"spill",tr:"dökmek"});
medium.push({ eng:"spoil",tr:"berbat etmek"});
medium.push({ eng:"spray",tr:"püskürtmek"});
medium.push({ eng:"stain",tr:"lekelemek"});
medium.push({ eng:"stamp",tr:"damgalamak"});
medium.push({ eng:"stare",tr:"dik dik bakmak"});
medium.push({ eng:"start",tr:"başlamak"});
medium.push({ eng:"stay",tr:"kalmak"});
medium.push({ eng:"steer",tr:"dümen kullanmak"});
medium.push({ eng:"step",tr:"adım atmak"});
medium.push({ eng:"stitch",tr:"dikiş dikmek"});
medium.push({ eng:"stop",tr:"durmak"});
medium.push({ eng:"store",tr:"depolamak"});
medium.push({ eng:"strap",tr:"kayışla bağlamak"});
medium.push({ eng:"strengthen",tr:"güçlendirmek"});
medium.push({ eng:"stretch",tr:"germek"});
medium.push({ eng:"strip",tr:"soymak"});
medium.push({ eng:"stroke",tr:"okşamak"});
medium.push({ eng:"stuff",tr:"doldurmak/tıkmak"});
medium.push({ eng:"succeed",tr:"başarmak"});
medium.push({ eng:"suck",tr:"emmek"});
medium.push({ eng:"suffer",tr:"ıstırap çekmek"});
medium.push({ eng:"suggest",tr:"tavsiye etmek"});
medium.push({ eng:"suit",tr:"uymak"});
medium.push({ eng:"supply",tr:"tedarik etmek"});
medium.push({ eng:"support",tr:"desteklemek"});
medium.push({ eng:"suppose",tr:"varsaymak/zannetmek"});
medium.push({ eng:"surprise",tr:"şaşırmak"});
medium.push({ eng:"surround",tr:"kuşatmak"});
medium.push({ eng:"suspect",tr:"şüphelenmek"});
medium.push({ eng:"suspend",tr:"askıya almak/asmak"});
medium.push({ eng:"switch",tr:"değiştirmek/düğmeye basmak"});
medium.push({ eng:"talk",tr:"konuşmak"});
medium.push({ eng:"tap",tr:"kullanmak"});
medium.push({ eng:"taste",tr:"tadına bakmak"});
medium.push({ eng:"tease",tr:"alay etmek"});
medium.push({ eng:"telephone",tr:"telefon etmek"});
medium.push({ eng:"tempt",tr:"ayartmak"});
medium.push({ eng:"terrify",tr:"çok korkutmak"});
medium.push({ eng:"test",tr:"test etmek"});
medium.push({ eng:"thank",tr:"teşekkür etmek"});
medium.push({ eng:"tick",tr:"tik koymak"});
medium.push({ eng:"tie",tr:"bağlamak"});
medium.push({ eng:"time",tr:"zamanlamak"});
medium.push({ eng:"tip",tr:"bahşiş vermek"});
medium.push({ eng:"tire",tr:"yormak/yorulmak"});
medium.push({ eng:"touch",tr:"dokunmak"});
medium.push({ eng:"tour",tr:"dolaşmak"});
medium.push({ eng:"trade",tr:"ticaret yapmak"});
medium.push({ eng:"train",tr:"eğitmek"});
medium.push({ eng:"transport",tr:"nakletmek"});
medium.push({ eng:"trap",tr:"tuzağa düşürmek"});
medium.push({ eng:"travel",tr:"seyahat etmek"});
medium.push({ eng:"treat",tr:"muamele etmek"});
medium.push({ eng:"tremble",tr:"titremek"});
medium.push({ eng:"trick",tr:"aldatmak"});
medium.push({ eng:"trip",tr:"çelme takmak"});
medium.push({ eng:"trot",tr:"tırıs gitmek"});
medium.push({ eng:"trouble",tr:"rahatsız etmek"});
medium.push({ eng:"trust",tr:"güvenmek"});
medium.push({ eng:"try",tr:"denemek"});
medium.push({ eng:"tug",tr:"şiddetle çekmek"});
medium.push({ eng:"turn",tr:"dönmek"});
medium.push({ eng:"twist",tr:"bükmek/kıvırmak"});
medium.push({ eng:"type",tr:"daktilo ile yazmak"});
medium.push({ eng:"undress",tr:"soyunmak"});
medium.push({ eng:"unite",tr:"birleşmek/birleştirmek"});
medium.push({ eng:"unlock",tr:"kilidini açmak"});
medium.push({ eng:"unpack",tr:"(bavul) açmak"});
medium.push({ eng:"use",tr:"kullanmak"});
medium.push({ eng:"visit",tr:"ziyaret etmek"});
medium.push({ eng:"wait",tr:"beklemek"});
medium.push({ eng:"walk",tr:"yürümek"});
medium.push({ eng:"want",tr:"istemek"});
medium.push({ eng:"warm",tr:"ısınmak/heyecanlandırmak"});
medium.push({ eng:"warn",tr:"uyarmak"});
medium.push({ eng:"wash",tr:"yıkamak"});
medium.push({ eng:"waste",tr:"ziyan etmek"});
medium.push({ eng:"watch",tr:"seyretmek"});
medium.push({ eng:"water",tr:"sulamak"});
medium.push({ eng:"wave",tr:"sallamak/sallanmak"});
medium.push({ eng:"weigh",tr:"tartmak/çekmek"});
medium.push({ eng:"welcome",tr:"hoş karşılamak"});
medium.push({ eng:"whisper",tr:"fısıldamak"});
medium.push({ eng:"whistle",tr:"ıslık çalmak"});
medium.push({ eng:"wink",tr:"göz kırpmak"});
medium.push({ eng:"wipe",tr:"silmek"});
medium.push({ eng:"wish",tr:"dilemek"});
medium.push({ eng:"wonder",tr:"hayret etmek"});
medium.push({ eng:"work",tr:"çalışmak"});
medium.push({ eng:"worry",tr:"endişelenmek"});
medium.push({ eng:"wrestle",tr:"güreşmek"});
medium.push({ eng:"yawn",tr:"esnemek"});
medium.push({ eng:"yell",tr:"haykırmak"});
medium.push({ eng:"zip",tr:"fermuar açmak/kapamak"});
medium.push({ eng:"zoom",tr:"zum yapmak "});

var hard = [];

hard.push({ eng:"Accept",tr:"kabul etmek"});
hard.push({ eng:"Add",tr:"eklemek"});
hard.push({ eng:"Admire",tr:"hayran olmak"});
hard.push({ eng:"Admit",tr:"itiraf etmek"});
hard.push({ eng:"Advise",tr:"tavsiye etmek"});
hard.push({ eng:"Afford",tr:"karşılamak"});
hard.push({ eng:"Agree",tr:"aynı fikirde olmak"});
hard.push({ eng:"Alert",tr:"alarma geçirmek"});
hard.push({ eng:"Allow",tr:"izin vermek"});
hard.push({ eng:"Amuse",tr:"eğlendirmek"});
hard.push({ eng:"Analyse",tr:"incelemek"});
hard.push({ eng:"Announce",tr:"duyurmak"});
hard.push({ eng:"Annoy",tr:"rahatsız etmek"});
hard.push({ eng:"Answer",tr:"cevap vermek"});
hard.push({ eng:"Apologise",tr:"özür dilemek"});
hard.push({ eng:"Appear",tr:"gözükmek"});
hard.push({ eng:"Applaud",tr:"alkışlamak"});
hard.push({ eng:"Appreciate",tr:"memnun olmak"});
hard.push({ eng:"Approve",tr:"onaylamak"});
hard.push({ eng:"Argue",tr:"tartışmak"});
hard.push({ eng:"Arrange",tr:"düzenlemek"});
hard.push({ eng:"Arrest",tr:"tutuklamak"});
hard.push({ eng:"Arrive",tr:"varmak"});
hard.push({ eng:"Ask",tr:"sormak"});
hard.push({ eng:"Attach",tr:"iliştirmek"});
hard.push({ eng:"Attack",tr:"saldırmak"});
hard.push({ eng:"Attempt",tr:"girişimde bulunmak"});
hard.push({ eng:"Attend",tr:"katılmak"});
hard.push({ eng:"Attract",tr:"çekmek"});
hard.push({ eng:"Avoid",tr:"sakınmak"});
hard.push({ eng:"Back",tr:"geriye gitmek"});
hard.push({ eng:"Bake",tr:"pişirmek"});
hard.push({ eng:"Balance",tr:"dengelemek"});
hard.push({ eng:"Ban",tr:"yasaklamak"});
hard.push({ eng:"Bang",tr:"vurmak/çarpmak"});
hard.push({ eng:"Bare",tr:"açığa çıkarmak"});
hard.push({ eng:"Bat",tr:"sopayla vurmak"});
hard.push({ eng:"Bathe",tr:"banyo yapmak"});
hard.push({ eng:"Battle",tr:"savaşmak"});
hard.push({ eng:"Beam",tr:"parıldamak"});
hard.push({ eng:"Beg",tr:"özür dilemek"});
hard.push({ eng:"Behave",tr:"davranmak"});
hard.push({ eng:"Belong",tr:"ait olmak"});
hard.push({ eng:"Bleach",tr:"ağartmak"});
hard.push({ eng:"Bless",tr:"kutsamak"});
hard.push({ eng:"Blind",tr:"körleştirmek"});
hard.push({ eng:"Blink",tr:"göz kırpmak"});
hard.push({ eng:"Blot",tr:"lekelemek"});
hard.push({ eng:"Blush",tr:"utançtan kızarmak"});
hard.push({ eng:"Boast",tr:"böbürlenmek"});
hard.push({ eng:"Boil",tr:"kaynamak"});
hard.push({ eng:"Bolt",tr:"irkilmek"});
hard.push({ eng:"Bomb",tr:"bombalamak"});
hard.push({ eng:"Book",tr:"rezervasyon yapmak"});
hard.push({ eng:"Bore",tr:"canını sıkmak"});
hard.push({ eng:"Borrow",tr:"ödünç almak"});
hard.push({ eng:"Bounce",tr:"zıplamak"});
hard.push({ eng:"Bow",tr:"reverans yapmak"});
hard.push({ eng:"Box",tr:"yumruklaşmak"});
hard.push({ eng:"Brake",tr:"fren yapmak"});
hard.push({ eng:"Branch",tr:"dallanmak"});
hard.push({ eng:"Breathe",tr:"nefes almak"});
hard.push({ eng:"Bruise",tr:"çürütmek"});
hard.push({ eng:"Brush",tr:"fırçalamak"});
hard.push({ eng:"Bubble",tr:"fokurdamak"});
hard.push({ eng:"Bump",tr:"toslamak"});
hard.push({ eng:"Burn",tr:"yanmak"});
hard.push({ eng:"Bury",tr:"gömmek"});
hard.push({ eng:"Buzz",tr:"vızıldamak"});
hard.push({ eng:"Calculate",tr:"hesaplamak"});
hard.push({ eng:"Call",tr:"aramak"});
hard.push({ eng:"Camp",tr:"kamp yapmak"});
hard.push({ eng:"Care",tr:"önemsemek"});
hard.push({ eng:"Carry",tr:"taşımak"});
hard.push({ eng:"Carve",tr:"oymak"});
hard.push({ eng:"Cause",tr:"neden olmak"});
hard.push({ eng:"Challenge",tr:"meydan okumak"});
hard.push({ eng:"Change",tr:"değiştirmek"});
hard.push({ eng:"Charge",tr:"şarj etmek"});
hard.push({ eng:"Chase",tr:"kovalamak"});
hard.push({ eng:"Cheat",tr:"aldatmak"});
hard.push({ eng:"Check",tr:"kontrol etmek"});
hard.push({ eng:"Cheer",tr:"tezahürat yapmak"});
hard.push({ eng:"Chew",tr:"çiğnemek"});
hard.push({ eng:"Choke",tr:"tıkamak"});
hard.push({ eng:"Chop",tr:"doğramak"});
hard.push({ eng:"Claim",tr:"iddia etmek"});
hard.push({ eng:"Clap",tr:"alkışlamak"});
hard.push({ eng:"Clean",tr:"temizlemek"});
hard.push({ eng:"Clear",tr:"temizlemek"});
hard.push({ eng:"Clip",tr:"tutturmak"});
hard.push({ eng:"Close",tr:"kapatmak"});
hard.push({ eng:"Coach",tr:"yetiştirmek/çalıştırmak"});
hard.push({ eng:"Coil",tr:"dolanmak"});
hard.push({ eng:"Collect",tr:"biriktirmek"});
hard.push({ eng:"Colour",tr:"renklendirmek"});
hard.push({ eng:"Comb",tr:"taramak"});
hard.push({ eng:"Command",tr:"emir vermek"});
hard.push({ eng:"Communicate",tr:"iletişim kurmak"});
hard.push({ eng:"Compare",tr:"karşılaştırmak"});
hard.push({ eng:"Compete",tr:"yarışmak"});
hard.push({ eng:"Complain",tr:"yakınmak"});
hard.push({ eng:"Complete",tr:"tamamlamak"});
hard.push({ eng:"Concentrate",tr:"konsantre olmak"});
hard.push({ eng:"Concern",tr:"kaygılandırmak"});
hard.push({ eng:"Confess",tr:"itiraf etmek"});
hard.push({ eng:"Confuse",tr:"kafasını karıştırmak"});
hard.push({ eng:"Connect",tr:"bağlamak"});
hard.push({ eng:"Consider",tr:"hesaba katmak"});
hard.push({ eng:"Consist",tr:"-den oluşmak"});
hard.push({ eng:"Contain",tr:"içermek"});
hard.push({ eng:"Continue",tr:"devam etmek"});
hard.push({ eng:"Copy",tr:"kopyalamak"});
hard.push({ eng:"Correct",tr:"düzeltmek"});
hard.push({ eng:"Cough",tr:"öksürmek"});
hard.push({ eng:"Count",tr:"saymak"});
hard.push({ eng:"Cover",tr:"örtmek"});
hard.push({ eng:"Crack",tr:"çatlamak/çatlatmak"});
hard.push({ eng:"Crash",tr:"gürültüyle çarpma"});
hard.push({ eng:"Crawl",tr:"emeklemek"});
hard.push({ eng:"Cross",tr:"öbür tarafa geçmek"});
hard.push({ eng:"Crush",tr:"ezmek"});
hard.push({ eng:"Cry",tr:"ağlamak"});
hard.push({ eng:"Cure",tr:"tedavi etmek"});
hard.push({ eng:"Curl",tr:"kıvrılmak/bükülmek"});
hard.push({ eng:"Curve",tr:"eğmek/eğilmek"});
hard.push({ eng:"Cycle",tr:"bisiklet sürmek"});
hard.push({ eng:"Dam",tr:"set çekmek"});
hard.push({ eng:"Damage",tr:"hasar vermek"});
hard.push({ eng:"Dance",tr:"dansetmek"});
hard.push({ eng:"Dare",tr:"cüret etmek"});
hard.push({ eng:"Decay",tr:"bozmak/çürütmek"});
hard.push({ eng:"Deceive",tr:"aldatmak"});
hard.push({ eng:"Decide",tr:"karar vermek"});
hard.push({ eng:"Decorate",tr:"dekore etmek"});
hard.push({ eng:"Delay",tr:"gecikmek/geciktirmek"});
hard.push({ eng:"Delight",tr:"zevk vermek"});
hard.push({ eng:"Deliver",tr:"teslim etmek"});
hard.push({ eng:"Depend",tr:"bağlı olmak"});
hard.push({ eng:"Describe",tr:"tanımlamak"});
hard.push({ eng:"Desert",tr:"terketmek"});
hard.push({ eng:"Deserve",tr:"layık olmak"});
hard.push({ eng:"Destroy",tr:"mahvetmek"});
hard.push({ eng:"Detect",tr:"tespit etmek"});
hard.push({ eng:"Develop",tr:"geliştirmek"});
hard.push({ eng:"Disagree",tr:"aynı fikirde olmamak"});
hard.push({ eng:"Disappear",tr:"gözden kaybolmak"});
hard.push({ eng:"Disapprove",tr:"tasvip etmemek"});
hard.push({ eng:"Disarm",tr:"silahsızandırmak"});
hard.push({ eng:"Discover",tr:"keşfetmek"});
hard.push({ eng:"Dislike",tr:"hoşlanmamak"});
hard.push({ eng:"Divide",tr:"bölmek"});
hard.push({ eng:"Double",tr:"iki misli yapmak"});
hard.push({ eng:"Doubt",tr:"-den kuşkulanmak"});
hard.push({ eng:"Drag",tr:"sürüklemek"});
hard.push({ eng:"Drain",tr:"akıtmak/akmak"});
hard.push({ eng:"Dream",tr:"rüya görmek/hayal kurmak"});
hard.push({ eng:"Dress",tr:"giyinmek"});
hard.push({ eng:"Drip",tr:"damlamak"});
hard.push({ eng:"Drop",tr:"düşürmek"});
hard.push({ eng:"Drown",tr:"boğulmak"});
hard.push({ eng:"Drum",tr:"davul çalmak"});
hard.push({ eng:"Dry",tr:"kurumak/kurutmak"});
hard.push({ eng:"Dust",tr:"tozunu almak"});
hard.push({ eng:"Earn",tr:"kazanmak"});
hard.push({ eng:"Educate",tr:"eğitmek"});
hard.push({ eng:"Embarrass",tr:"utandırmak"});
hard.push({ eng:"Employ",tr:"iş vermek"});
hard.push({ eng:"Empty",tr:"boşaltmak"});
hard.push({ eng:"Encourage",tr:"cesaretlendirmek"});
hard.push({ eng:"End",tr:"bitirmek"});
hard.push({ eng:"Enjoy",tr:"zevk almak"});
hard.push({ eng:"Enter",tr:"girmek"});
hard.push({ eng:"Entertain",tr:"eğlendirmek"});
hard.push({ eng:"Escape",tr:"kaçmak"});
hard.push({ eng:"Examine",tr:"muayene etmek"});
hard.push({ eng:"Excite",tr:"heyecanlandırmak"});
hard.push({ eng:"Excuse",tr:"bağışlamak"});
hard.push({ eng:"Exercise",tr:"egzersiz yapmak"});
hard.push({ eng:"Exist",tr:"var olmak"});
hard.push({ eng:"Expand",tr:"genişletmek"});
hard.push({ eng:"Expect",tr:"ummak/beklemek"});
hard.push({ eng:"Explain",tr:"açıklamak"});
hard.push({ eng:"Explode",tr:"patlamak"});
hard.push({ eng:"Extend",tr:"erişmek/yayılmak"});
hard.push({ eng:"Face",tr:"yüzleşmek"});
hard.push({ eng:"Fade",tr:"solmak"});
hard.push({ eng:"Fail",tr:"başarısız olmak"});
hard.push({ eng:"Fancy",tr:"imgelemek"});
hard.push({ eng:"Fasten",tr:"bağlamak/tutturmak"});
hard.push({ eng:"Fax",tr:"faks çekmek"});
hard.push({ eng:"Fear",tr:"korkmak"});
hard.push({ eng:"Fence",tr:"çitle çevirmek"});
hard.push({ eng:"Fetch",tr:"gidip getirmek"});
hard.push({ eng:"File",tr:"dosyalamak"});
hard.push({ eng:"Fill",tr:"doldurmak"});
hard.push({ eng:"Film",tr:"film çekmek"});
hard.push({ eng:"Fire",tr:"tutuşturmak/ateş etmek"});
hard.push({ eng:"Fit",tr:"(giysi) uymak"});
hard.push({ eng:"Fix",tr:"sabitlemek/belirlemek"});
hard.push({ eng:"Flap",tr:"kanat çırpmak"});
hard.push({ eng:"Flash",tr:"birden parlamak"});
hard.push({ eng:"Float",tr:"batmadan yüzmek"});
hard.push({ eng:"Flood",tr:"su basmak"});
hard.push({ eng:"Flow",tr:"akmak"});
hard.push({ eng:"Flower",tr:"çiçek açmak"});
hard.push({ eng:"Fold",tr:"katlamak"});
hard.push({ eng:"Follow",tr:"takip etmek"});
hard.push({ eng:"Fool",tr:"kandırmak"});
hard.push({ eng:"Force",tr:"zorlamak"});
hard.push({ eng:"Form",tr:"biçimlendirmek"});
hard.push({ eng:"Found",tr:"inşa etmek"});
hard.push({ eng:"Frame",tr:"çerçevelemek"});
hard.push({ eng:"Frighten",tr:"korkutmak"});
hard.push({ eng:"Fry",tr:"kızartmak"});
hard.push({ eng:"Gather",tr:"toplanmak"});
hard.push({ eng:"Gaze",tr:"gözünü dikerek bakmak"});
hard.push({ eng:"Glow",tr:"ışık vermek"});
hard.push({ eng:"Glue",tr:"yapıştırmak"});
hard.push({ eng:"Grab",tr:"kavramak"});
hard.push({ eng:"Grate",tr:"rendelemek"});
hard.push({ eng:"Grease",tr:"yağlamak"});
hard.push({ eng:"Greet",tr:"selamlamak/karşılamak"});
hard.push({ eng:"Grin",tr:"sırıtmak"});
hard.push({ eng:"Grip",tr:"sımsıkı tutmak"});
hard.push({ eng:"Groan",tr:"inlemek"});
hard.push({ eng:"Guarantee",tr:"garanti vermek"});
hard.push({ eng:"Guard",tr:"korumak"});
hard.push({ eng:"Guess",tr:"tahmin etmek"});
hard.push({ eng:"Guide",tr:"kılavuzluk etmek"});
hard.push({ eng:"Hammer",tr:"çekiçle vurmak"});
hard.push({ eng:"Hand",tr:"uzatmak"});
hard.push({ eng:"Handle",tr:"başa çıkmak/yönetmek"});
hard.push({ eng:"Hang",tr:"asmak"});
hard.push({ eng:"Happen",tr:"olmak"});
hard.push({ eng:"Harass",tr:"usandırmak"});
hard.push({ eng:"Harm",tr:"zarar vermek"});
hard.push({ eng:"Hate",tr:"efret etmek"});
hard.push({ eng:"Haunt",tr:"(cin",tr:"peri) uğramak"});
hard.push({ eng:"Head",tr:"başı çekmek"});
hard.push({ eng:"Heal",tr:"iyileşmek"});
hard.push({ eng:"Heap",tr:"kümelemek"});
hard.push({ eng:"Heat",tr:"ısıtmak"});
hard.push({ eng:"Help",tr:"yardım etmek"});
hard.push({ eng:"Hook",tr:"çengellemek"});
hard.push({ eng:"Hop",tr:"hoplamak"});
hard.push({ eng:"Hope",tr:"ümit etmek"});
hard.push({ eng:"Hover",tr:"havada durmak"});
hard.push({ eng:"Hug",tr:"kucaklamak"});
hard.push({ eng:"Hum",tr:"vızıldamak"});
hard.push({ eng:"Hunt",tr:"avlanmak"});
hard.push({ eng:"Hurry",tr:"acele etmek"});
hard.push({ eng:"Identify",tr:"teşhis etmek"});
hard.push({ eng:"Ignore",tr:"önemsememek"});
hard.push({ eng:"Imagine",tr:"hayal etmek"});
hard.push({ eng:"Impress",tr:"etkilemek"});
hard.push({ eng:"Improve",tr:"geliştirmek"});
hard.push({ eng:"Include",tr:"içermek"});
hard.push({ eng:"Increase",tr:"artmak"});
hard.push({ eng:"Influence",tr:"etkilemek"});
hard.push({ eng:"Inform",tr:"bilgilendirmek"});
hard.push({ eng:"Inject",tr:"iğne yapmak"});
hard.push({ eng:"Injure",tr:"incitmek/yaralamak"});
hard.push({ eng:"Instruct",tr:"talimat vermek"});
hard.push({ eng:"Intend",tr:"niyet etmek"});
hard.push({ eng:"Interest",tr:"ilgi uyandırmak"});
hard.push({ eng:"Interfere",tr:"yoluna çıkmak/engellemek"});
hard.push({ eng:"Interrupt",tr:"yarıda kesmek"});
hard.push({ eng:"Introduce",tr:"tanıştırmak"});
hard.push({ eng:"Invent",tr:"bulmak/keşfetmek"});
hard.push({ eng:"Invite",tr:"davet etmek"});
hard.push({ eng:"Irritate",tr:"kızdırmak"});
hard.push({ eng:"Itch",tr:"kaşımak"});
hard.push({ eng:"Jail",tr:"hapsetmek"});
hard.push({ eng:"Jam",tr:"sıkıştırmak/tıkamak"});
hard.push({ eng:"Jog",tr:"dürtmek/itmek"});
hard.push({ eng:"Join",tr:"katılmak"});
hard.push({ eng:"Joke",tr:"şaka yapmak"});
hard.push({ eng:"Judge",tr:"yargılamak"});
hard.push({ eng:"Juggle",tr:"hile yapmak"});
hard.push({ eng:"Jump",tr:"zıplamak"});
hard.push({ eng:"Kick",tr:"tekmelemek"});
hard.push({ eng:"Kill",tr:"öldürmek"});
hard.push({ eng:"Kiss",tr:"öpmek"});
hard.push({ eng:"Kneel",tr:"diz çökmek"});
hard.push({ eng:"Knit",tr:"örmek"});
hard.push({ eng:"Knock",tr:"vurmak"});
hard.push({ eng:"Knot",tr:"düğümlemek"});
hard.push({ eng:"Label",tr:"etiketlemek"});
hard.push({ eng:"Land",tr:"iniş yapmak"});
hard.push({ eng:"Last",tr:"sürmek"});
hard.push({ eng:"Laugh",tr:"gülmek"});
hard.push({ eng:"Launch",tr:"(roket) fırlatmak"});
hard.push({ eng:"Learn",tr:"öğrenmek"});
hard.push({ eng:"Level",tr:"düzleştirmek"});
hard.push({ eng:"License",tr:"ruhsat vermek"});
hard.push({ eng:"Lick",tr:"yalamak"});
hard.push({ eng:"Lie",tr:"yalan söylemek"});
hard.push({ eng:"Lighten",tr:"aydınlatmak"});
hard.push({ eng:"Like",tr:"hoşlanmak"});
hard.push({ eng:"List",tr:"listelemek"});
hard.push({ eng:"Listen",tr:"dinlemek"});
hard.push({ eng:"Live",tr:"yaşamak"});
hard.push({ eng:"Load",tr:"yüklemek"});
hard.push({ eng:"Lock",tr:"kilitlemek"});
hard.push({ eng:"Long",tr:"can atmak"});
hard.push({ eng:"Look",tr:"bakmak"});
hard.push({ eng:"Love",tr:"sevmek"});
hard.push({ eng:"Man",tr:"adam vermek"});
hard.push({ eng:"Manage",tr:"yönetmek"});
hard.push({ eng:"March",tr:"uygun adım yürümek"});
hard.push({ eng:"Mark",tr:"işaretlemek"});
hard.push({ eng:"Marry",tr:"evlenmek"});
hard.push({ eng:"Match",tr:"eşleştirmek"});
hard.push({ eng:"Mate",tr:"çiftleşmek"});
hard.push({ eng:""});
hard.push({ eng:""});
hard.push({ eng:"Matter",tr:"önemli olmak"});
hard.push({ eng:"Measure",tr:"ölç mek"});
hard.push({ eng:"Meddle",tr:"burnunu sokmak"});
hard.push({ eng:"Melt",tr:"erimek"});
hard.push({ eng:"Memorise",tr:"ezberlemek"});
hard.push({ eng:"Mend",tr:"tamir etmek"});
hard.push({ eng:"mess up",tr:"dağıtmak"});
hard.push({ eng:"milk",tr:"süt sağmak"});
hard.push({ eng:"mine",tr:"maden işletmek"});
hard.push({ eng:"miss",tr:"özlemek/kaçırmak"});
hard.push({ eng:"mix",tr:"karıştırmak"});
hard.push({ eng:"moan",tr:"sızlanmak"});
hard.push({ eng:"moor",tr:"palamarla bağlamak"});
hard.push({ eng:"mourn",tr:"yasını tutmak"});
hard.push({ eng:"move",tr:"taşınmak"});
hard.push({ eng:"muddle",tr:"karıştırmak"});
hard.push({ eng:"mug",tr:"saldırıp soymak"});
hard.push({ eng:"multiply",tr:"çoğalmak"});
hard.push({ eng:"murder",tr:"cinayet işlemek"});
hard.push({ eng:"nail",tr:"çivilemek"});
hard.push({ eng:"name",tr:"ad vermek"});
hard.push({ eng:"need",tr:"ihtiyaç duymak"});
hard.push({ eng:"nest",tr:"yuva yapmak"});
hard.push({ eng:"nod",tr:"başını sallamak"});
hard.push({ eng:"note",tr:"not etmek"});
hard.push({ eng:"notice",tr:"farkına varmak"});
hard.push({ eng:"number",tr:"numaralamak"});
hard.push({ eng:"obey",tr:"itaat etmek"});
hard.push({ eng:"object",tr:"itiraz etmek"});
hard.push({ eng:"observe",tr:"incelemek"});
hard.push({ eng:"obtain",tr:"elde etmek"});
hard.push({ eng:"occur",tr:"meydana gelmek"});
hard.push({ eng:"offend",tr:"gücendirmek"});
hard.push({ eng:"offer",tr:"teklif etmek"});
hard.push({ eng:"open",tr:"açmak"});
hard.push({ eng:"order",tr:"ısmarlamak"});
hard.push({ eng:"overflow",tr:"taşmak"});
hard.push({ eng:"owe",tr:"borcu olmak"});
hard.push({ eng:"own",tr:"sahip olmak"});
hard.push({ eng:"pack",tr:"paket yapmak"});
hard.push({ eng:"paddle",tr:"sude gezinmek"});
hard.push({ eng:"paint",tr:"boyamak"});
hard.push({ eng:"park",tr:"park etmek"});
hard.push({ eng:"part",tr:"ayırmak/ayrılmak"});
hard.push({ eng:"pass",tr:"geçmek"});
hard.push({ eng:"paste",tr:"yapıştırmak"});
hard.push({ eng:"pat",tr:"hafifçe vurmak"});
hard.push({ eng:"pause",tr:"duraklamak"});
hard.push({ eng:"peck",tr:"gagalamak"});
hard.push({ eng:"peel",tr:"kabuğunu soymak"});
hard.push({ eng:"peep",tr:"röntgenlemek"});
hard.push({ eng:"perform",tr:"temsil etmek"});
hard.push({ eng:"permit",tr:"izin vermek"});
hard.push({ eng:"phone",tr:"telefon açmak"});
hard.push({ eng:"pick",tr:"seçmek/ayırmak"});
hard.push({ eng:"pinch",tr:"çimdiklemek"});
hard.push({ eng:"pine",tr:"güçten düşmek"});
hard.push({ eng:"place",tr:"yerleştirmek"});
hard.push({ eng:"plan",tr:"planlamak"});
hard.push({ eng:"plant",tr:"yerleştirmek/ekmek"});
hard.push({ eng:"play",tr:"oynamak"});
hard.push({ eng:"please",tr:"memnun etmek"});
hard.push({ eng:"plug",tr:"tıkamak"});
hard.push({ eng:"point",tr:"işaret etmek"});
hard.push({ eng:"poke",tr:"sokmak/dürtmek"});
hard.push({ eng:"polish",tr:"parlatmak/cilalamak"});
hard.push({ eng:"pop",tr:"yerinden fırlamak"});
hard.push({ eng:"possess",tr:"sahip olmak"});
hard.push({ eng:"post",tr:"postalamak"});
hard.push({ eng:"pour",tr:"doldurmak"});
hard.push({ eng:"practise",tr:"pratik yapmak"});
hard.push({ eng:"pray",tr:"dua etmek"});
hard.push({ eng:"preach",tr:"vaaz etmek"});
hard.push({ eng:"precede",tr:"-den önce gelmek"});
hard.push({ eng:"prefer",tr:"tercih etmek"});
hard.push({ eng:"prepare",tr:"hazırlamak"});
hard.push({ eng:"present",tr:"takdim etmek/sunmak"});
hard.push({ eng:"preserve",tr:"korumak/saklamak"});
hard.push({ eng:"press",tr:"sıkıştırmak"});
hard.push({ eng:"pretend",tr:"-miş gibi yapmak"});
hard.push({ eng:"prevent",tr:"önlemek"});
hard.push({ eng:"prick",tr:"iğnelemek"});
hard.push({ eng:"print",tr:"basmak"});
hard.push({ eng:"produce",tr:"üretmek"});
hard.push({ eng:"program",tr:"programlamak"});
hard.push({ eng:"promise",tr:"söz vermek"});
hard.push({ eng:"protect",tr:"korumak"});
hard.push({ eng:"provide",tr:"sağlamak"});
hard.push({ eng:"pull",tr:"çekmek"});
hard.push({ eng:"pump",tr:"pompalamak"});
hard.push({ eng:"punch",tr:"yumruk atmak"});
hard.push({ eng:"puncture",tr:"delik açmak"});
hard.push({ eng:"punish",tr:"cezalandırmak"});
hard.push({ eng:"push",tr:"itmek"});
hard.push({ eng:"question",tr:"soru sormak"});
hard.push({ eng:"queue",tr:"kuyruğa girmek"});
hard.push({ eng:"race",tr:"yarışmak"});
hard.push({ eng:"radiate",tr:"ışık saçmak"});
hard.push({ eng:"rain",tr:"yağmur yağmak"});
hard.push({ eng:"raise",tr:"kaldırmak"});
hard.push({ eng:"reach",tr:"ulaşmak"});
hard.push({ eng:"realise",tr:"farkına varmak"});
hard.push({ eng:"receive",tr:"teslim almak"});
hard.push({ eng:"recognise",tr:"tanımak/takdir etmek"});
hard.push({ eng:"record",tr:"kaydetmek"});
hard.push({ eng:"reduce",tr:"azaltmak/indirmek"});
hard.push({ eng:"reflect",tr:"yansıtmak"});
hard.push({ eng:"refuse",tr:"reddetmek"});
hard.push({ eng:"regret",tr:"ihmal etmek"});
hard.push({ eng:"reign",tr:"saltanat sürmek"});
hard.push({ eng:"reject",tr:"reddetmek/atmak"});
hard.push({ eng:"rejoice",tr:"sevinmek"});
hard.push({ eng:"relax",tr:"rahatlamak"});
hard.push({ eng:"release",tr:"serbest bırakmak"});
hard.push({ eng:"rely",tr:"itimat etmek"});
hard.push({ eng:"remain",tr:"kalmak"});
hard.push({ eng:"remember",tr:"hatırlamak"});
hard.push({ eng:"remind",tr:"hatırlatmak"});
hard.push({ eng:"remove",tr:"çıkarmak/temizlemek"});
hard.push({ eng:"repair",tr:"tamir etmek"});
hard.push({ eng:"repeat",tr:"tamir etmek"});
hard.push({ eng:"replace",tr:"eski yerine koymak"});
hard.push({ eng:"reply",tr:"karşılık vermek"});
hard.push({ eng:"report",tr:"haber vermek"});
hard.push({ eng:"reproduce",tr:"üretmek"});
hard.push({ eng:"request",tr:"rica etmek"});
hard.push({ eng:"rescue",tr:"kurtarmak"});
hard.push({ eng:"retire",tr:"emekli olmak"});
hard.push({ eng:"return",tr:"dönmek/geri vermek"});
hard.push({ eng:"rhyme",tr:"ile uyak oluşturmak"});
hard.push({ eng:"rinse",tr:"durulamak"});
hard.push({ eng:"risk",tr:"risk almak"});
hard.push({ eng:"rob",tr:"soymak/çalmak"});
hard.push({ eng:"rock",tr:"sallamak"});
hard.push({ eng:"roll",tr:"yuvarlamak"});
hard.push({ eng:"rot",tr:"çürümek"});
hard.push({ eng:"rub",tr:"ovalamak"});
hard.push({ eng:"ruin",tr:"harab etmek"});
hard.push({ eng:"rule",tr:"hükmetmek"});
hard.push({ eng:"rush",tr:"acele etmek"});
hard.push({ eng:"sack",tr:"işten atmak"});
hard.push({ eng:"sail",tr:"yelken açmak"});
hard.push({ eng:"satisfy",tr:"hoşnut etmek"});
hard.push({ eng:"save",tr:"kurtarmak"});
hard.push({ eng:"saw",tr:"testere ile kesmek"});
hard.push({ eng:"scare",tr:"korkutmak"});
hard.push({ eng:"scatter",tr:"serpmek/dağıtmak"});
hard.push({ eng:"scold",tr:"azarlamak"});
hard.push({ eng:"scorch",tr:"kavurmak"});
hard.push({ eng:"scrape",tr:"kazımak"});
hard.push({ eng:"scratch",tr:"tırmalamak"});
hard.push({ eng:"scream",tr:"çığlık atmak"});
hard.push({ eng:"screw",tr:"vidalamak"});
hard.push({ eng:"scribble",tr:"çiziktirmek"});
hard.push({ eng:"scrub",tr:"fırçalamak/ovalamak"});
hard.push({ eng:"seal",tr:"mühürlemek"});
hard.push({ eng:"search",tr:"araştırmak"});
hard.push({ eng:"separate",tr:"ayırmak"});
hard.push({ eng:"serve",tr:"hizmet etmek"});
hard.push({ eng:"settle",tr:"yerleşmek"});
hard.push({ eng:"shade",tr:"gölgelemek"});
hard.push({ eng:"share",tr:"paylaşmak"});
hard.push({ eng:"shave",tr:"traş olmak"});
hard.push({ eng:"shelter",tr:"barındırmak"});
hard.push({ eng:"shiver",tr:"ürpermek"});
hard.push({ eng:"shock",tr:"şok etmek"});
hard.push({ eng:"shop",tr:"alışveriş yapmak"});
hard.push({ eng:"shrug",tr:"omuz silkmek"});
hard.push({ eng:"sigh",tr:"iç çekmek"});
hard.push({ eng:"sign",tr:"imzalamak"});
hard.push({ eng:"signal",tr:"işaret vermek"});
hard.push({ eng:"sin",tr:"günah işlemek"});
hard.push({ eng:"sip",tr:"yudumlamak"});
hard.push({ eng:"ski",tr:"kayak yapmak"});
hard.push({ eng:"skip",tr:"zıplamak/sekmek"});
hard.push({ eng:"slap",tr:"tokatlamak"});
hard.push({ eng:"slip",tr:"kaymak"});
hard.push({ eng:"slow",tr:"yavaşlamak"});
hard.push({ eng:"smash",tr:"parçalamak"});
hard.push({ eng:"smell",tr:"koklamak"});
hard.push({ eng:"smile",tr:"gülümsemek"});
hard.push({ eng:"smoke",tr:"sigara içmek"});
hard.push({ eng:"snatch",tr:"kapmak/kavramak"});
hard.push({ eng:"sneeze",tr:"aksırmak"});
hard.push({ eng:"sniff",tr:"burnunu çekmek/koklamak"});
hard.push({ eng:"snore",tr:"horlamak"});
hard.push({ eng:"snow",tr:"kar yağmak"});
hard.push({ eng:"soak",tr:"iyice ıslanmak"});
hard.push({ eng:"soothe",tr:"yatıştırmak"});
hard.push({ eng:"sound",tr:"ses çıkarmak"});
hard.push({ eng:"spare",tr:"esirgemek"});
hard.push({ eng:"spark",tr:"kıvılcım saçmak"});
hard.push({ eng:"sparkle",tr:"parıldamak"});
hard.push({ eng:"spell",tr:"hecelemek"});
hard.push({ eng:"spill",tr:"dökmek"});
hard.push({ eng:"spoil",tr:"berbat etmek"});
hard.push({ eng:"spot",tr:"beneklemek/lekelemek"});
hard.push({ eng:"spray",tr:"püskürtmek"});
hard.push({ eng:"sprout",tr:"filizlenmek"});
hard.push({ eng:"squash",tr:"ezmek/sıkıştırmak"});
hard.push({ eng:"squeak",tr:"gıcırdamak"});
hard.push({ eng:"squeal",tr:"ciyaklamak"});
hard.push({ eng:"squeeze",tr:"sıkmak/ezmek"});
hard.push({ eng:"stain",tr:"lekelemek"});
hard.push({ eng:"stamp",tr:"damgalamak"});
hard.push({ eng:"stare",tr:"dik dik bakmak"});
hard.push({ eng:"start",tr:"başlamak"});
hard.push({ eng:"stay",tr:"kalmak"});
hard.push({ eng:"steer",tr:"dümen kullanmak"});
hard.push({ eng:"step",tr:"adım atmak"});
hard.push({ eng:"stir",tr:"kıpırdamak/karıştırmak"});
hard.push({ eng:"stitch",tr:"dikiş dikmek"});
hard.push({ eng:"stop",tr:"durmak"});
hard.push({ eng:"store",tr:"depolamak"});
hard.push({ eng:"strap",tr:"kayışla bağlamak"});
hard.push({ eng:"strengthen",tr:"güçlendirmek"});
hard.push({ eng:"stretch",tr:"germek"});
hard.push({ eng:"strip",tr:"soymak"});
hard.push({ eng:"stroke",tr:"okşamak"});
hard.push({ eng:"stuff",tr:"doldurmak/tıkmak"});
hard.push({ eng:"subtract",tr:"eksiltmek"});
hard.push({ eng:"succeed",tr:"başarmak"});
hard.push({ eng:"suck",tr:"emmek"});
hard.push({ eng:"suffer",tr:"ıstırap çekmek"});
hard.push({ eng:"suggest",tr:"tavsiye etmek"});
hard.push({ eng:"suit",tr:"uymak"});
hard.push({ eng:"supply",tr:"tedarik etmek"});
hard.push({ eng:"support",tr:"desteklemek"});
hard.push({ eng:"suppose",tr:"varsaymak/zannetmek"});
hard.push({ eng:"surprise",tr:"şaşırmak"});
hard.push({ eng:"surround",tr:"kuşatmak"});
hard.push({ eng:"suspect",tr:"şüphelenmek"});
hard.push({ eng:"suspend",tr:"askıya almak/asmak"});
hard.push({ eng:"switch",tr:"değiştirmek/düğmeye basmak"});
hard.push({ eng:""});
hard.push({ eng:"talk",tr:"konuşmak"});
hard.push({ eng:"tame",tr:"evcilleştirmek"});
hard.push({ eng:"tap",tr:"kullanmak"});
hard.push({ eng:"taste",tr:"tadına bakmak"});
hard.push({ eng:"tease",tr:"alay etmek"});
hard.push({ eng:"telephone",tr:"telefon etmek"});
hard.push({ eng:"tempt",tr:"ayartmak"});
hard.push({ eng:"terrify",tr:"çok korkutmak"});
hard.push({ eng:"test",tr:"test etmek"});
hard.push({ eng:"thank",tr:"teşekkür etmek"});
hard.push({ eng:"thaw",tr:"erimek/yakınlaşmak"});
hard.push({ eng:"tick",tr:"tik koymak"});
hard.push({ eng:"tickle",tr:"gıdıklamak"});
hard.push({ eng:"tie",tr:"bağlamak"});
hard.push({ eng:"time",tr:"zamanlamak"});
hard.push({ eng:"tip",tr:"bahşiş vermek"});
hard.push({ eng:"tire",tr:"yormak/yorulmak"});
hard.push({ eng:"touch",tr:"dokunmak"});
hard.push({ eng:"tour",tr:"dolaşmak"});
hard.push({ eng:"tow",tr:"yedekte çekmek"});
hard.push({ eng:"trace",tr:"izini sürmek"});
hard.push({ eng:"trade",tr:"ticaret yapmak"});
hard.push({ eng:"train",tr:"eğitmek"});
hard.push({ eng:"transport",tr:"nakletmek"});
hard.push({ eng:"trap",tr:"tuzağa düşürmek"});
hard.push({ eng:"travel",tr:"seyahat etmek"});
hard.push({ eng:"treat",tr:"muamele etmek"});
hard.push({ eng:"tremble",tr:"titremek"});
hard.push({ eng:"trick",tr:"aldatmak"});
hard.push({ eng:"trip",tr:"çelme takmak"});
hard.push({ eng:"trot",tr:"tırıs gitmek"});
hard.push({ eng:"trouble",tr:"rahatsız etmek"});
hard.push({ eng:"trust",tr:"güvenmek"});
hard.push({ eng:"try",tr:"denemek"});
hard.push({ eng:"tug",tr:"şiddetle çekmek"});
hard.push({ eng:"tumble",tr:"yuvarlanmak"});
hard.push({ eng:"turn",tr:"dönmek"});
hard.push({ eng:"twist",tr:"bükmek/kıvırmak"});
hard.push({ eng:"type",tr:"daktilo ile yazmak"});
hard.push({ eng:"undress",tr:"soyunmak"});
hard.push({ eng:"unite",tr:"birleşmek/birleştirmek"});
hard.push({ eng:"unlock",tr:"kilidini açmak"});
hard.push({ eng:"unpack",tr:"(bavul) açmak"});
hard.push({ eng:"use",tr:"kullanmak"});
hard.push({ eng:"vanish",tr:"gözden kaybolmak"});
hard.push({ eng:"visit",tr:"ziyaret etmek"});
hard.push({ eng:"wail",tr:"feryat etmek"});
hard.push({ eng:"wait",tr:"beklemek"});
hard.push({ eng:"walk",tr:"yürümek"});
hard.push({ eng:"wander",tr:"volta atmak"});
hard.push({ eng:"want",tr:"istemek"});
hard.push({ eng:"warm",tr:"ısınmak/heyecanlandırmak"});
hard.push({ eng:"warn",tr:"uyarmak"});
hard.push({ eng:"wash",tr:"yıkamak"});
hard.push({ eng:"waste",tr:"ziyan etmek"});
hard.push({ eng:"watch",tr:"seyretmek"});
hard.push({ eng:"water",tr:"sulamak"});
hard.push({ eng:"wave",tr:"sallamak/sallanmak"});
hard.push({ eng:"weigh",tr:"tartmak/çekmek"});
hard.push({ eng:"welcome",tr:"hoş karşılamak"});
hard.push({ eng:"whine",tr:"haykırmak"});
hard.push({ eng:"whip",tr:"kırbaçlamak"});
hard.push({ eng:"whirl",tr:"fırıl fırıl dönmek"});
hard.push({ eng:"whisper",tr:"fısıldamak"});
hard.push({ eng:"whistle",tr:"ıslık çalmak"});
hard.push({ eng:"wink",tr:"göz kırpmak"});
hard.push({ eng:"wipe",tr:"silmek"});
hard.push({ eng:"wish",tr:"dilemek"});
hard.push({ eng:"wobble",tr:"sallanmak/bocalamak"});
hard.push({ eng:"wonder",tr:"hayret etmek"});
hard.push({ eng:"work",tr:"çalışmak"});
hard.push({ eng:"worry",tr:"endişelenmek"});
hard.push({ eng:"wrap",tr:"paketlemek"});
hard.push({ eng:"wreck",tr:"mahvetmek"});
hard.push({ eng:"wrestle",tr:"güreşmek"});
hard.push({ eng:"wriggle",tr:"kıpır kıpır etmek"});
hard.push({ eng:"yawn",tr:"esnemek"});
hard.push({ eng:"yell",tr:"haykırmak"});
hard.push({ eng:"zip",tr:"fermuar açmak/kapamak"});
hard.push({ eng:"zoom",tr:"zum yapmak"});
