var basic=[];
var medium = [];
var hard = [];

basic.push({ eng:"awake",tr:"uyanık"});
basic.push({ eng:"beautiful",tr:"güzel"});
basic.push({ eng:"bright",tr:"parlak"});
basic.push({ eng:"broken",tr:"kırık"});
basic.push({ eng:"cheap",tr:"ucuz"});
basic.push({ eng:"clean",tr:"temiz"});
basic.push({ eng:"cold",tr:"soğuk"});
basic.push({ eng:"dark",tr:"karanlık"});
basic.push({ eng:"dead",tr:"ölü"});
basic.push({ eng:"deep",tr:"derin"});
basic.push({ eng:"different",tr:"farklı"});
basic.push({ eng:"dirty",tr:"kirli"});
basic.push({ eng:"dry",tr:"kuru"});
basic.push({ eng:"early",tr:"erken"});
basic.push({ eng:"equal",tr:"eşit"});
basic.push({ eng:"flat",tr:"düz"});
basic.push({ eng:"free",tr:"özgür"});
basic.push({ eng:"full",tr:"dolu"});
basic.push({ eng:"general",tr:"genel"});
basic.push({ eng:"good",tr:"iyi"});
basic.push({ eng:"great",tr:"mükemmel"});
basic.push({ eng:"happy",tr:"mutlu"});
basic.push({ eng:"healthy",tr:"sağlıklı"});
basic.push({ eng:"ill",tr:"hasta"});
basic.push({ eng:"important",tr:"önemli"});
basic.push({ eng:"kind",tr:"nazik"});
basic.push({ eng:"loose",tr:"gevşek"});
basic.push({ eng:"loud",tr:"yüksek ses"});
basic.push({ eng:"male",tr:"erkek"});
basic.push({ eng:"married",tr:"evli"});
basic.push({ eng:"narrow",tr:"dar"});
basic.push({ eng:"natural",tr:"doğal"});
basic.push({ eng:"new",tr:"yeni"});
basic.push({ eng:"political",tr:"siyasi"});
basic.push({ eng:"poor",tr:"fakir"});
basic.push({ eng:"possible",tr:"mümkün"});
basic.push({ eng:"private",tr:"özel"});
basic.push({ eng:"quick",tr:"hızlı"});
basic.push({ eng:"quiet",tr:"sessiz"});
basic.push({ eng:"ready",tr:"hazır"});
basic.push({ eng:"regular",tr:"düzenli"});
basic.push({ eng:"sad",tr:"üzgün"});
basic.push({ eng:"secret",tr:"gizli"});
basic.push({ eng:"short",tr:"kısa"});
basic.push({ eng:"simple",tr:"basit"});
basic.push({ eng:"slow",tr:"yavaş"});
basic.push({ eng:"soft",tr:"yumuşak"});
basic.push({ eng:"special",tr:"özel"});
basic.push({ eng:"strange",tr:"garip"});
basic.push({ eng:"strong",tr:"güçlü"});
basic.push({ eng:"sweet",tr:"tatlı"});
basic.push({ eng:"tall",tr:"uzun"});
basic.push({ eng:"thick",tr:"kalın"});
basic.push({ eng:"thin",tr:"zayıf"});
basic.push({ eng:"tight",tr:"dar"});
basic.push({ eng:"tired",tr:"yorgun"});
basic.push({ eng:"true",tr:"doğru"});
basic.push({ eng:"warm",tr:"ılık"});
basic.push({ eng:"wet",tr:"ıslak"});
basic.push({ eng:"wide",tr:"geniş"});
basic.push({ eng:"wrong",tr:"yanlış"});
basic.push({ eng:"young",tr:"genç "});

medium.push({ eng:"Able",tr:"güçlü"});
medium.push({ eng:"Abnormal",tr:"anormal"});
medium.push({ eng:"Absent",tr:"yok"});
medium.push({ eng:"Absolute",tr:"mükemmel/tam"});
medium.push({ eng:"Acceptable",tr:"makul"});
medium.push({ eng:"Accessible",tr:"ulaşılabilir"});
medium.push({ eng:"Active",tr:"faal"});
medium.push({ eng:"Additional",tr:"ilave/ek"});
medium.push({ eng:"Adequate",tr:"yeterli"});
medium.push({ eng:"Advantageous",tr:"avantajlı"});
medium.push({ eng:"Advisable",tr:"önerilen"});
medium.push({ eng:"Affirmative",tr:"olumlu"});
medium.push({ eng:"Ago",tr:"önce"});
medium.push({ eng:"All",tr:"tüm"});
medium.push({ eng:"Alone",tr:"yalnız"});
medium.push({ eng:"Alphabetical",tr:"alfabetik"});
medium.push({ eng:"American",tr:"Amerikan"});
medium.push({ eng:"Angry",tr:"kızgın"});
medium.push({ eng:"Annual",tr:"yıllık"});
medium.push({ eng:"Another",tr:"başka"});
medium.push({ eng:"Any",tr:"hiç"});
medium.push({ eng:"Apparent",tr:"anlaşılır/açık"});
medium.push({ eng:"Applicable",tr:"uygulanabilir"});
medium.push({ eng:"Appreciable",tr:"kayda değer"});
medium.push({ eng:"Appropriate",tr:"uygun"});
medium.push({ eng:"Artificial",tr:"yapay"});
medium.push({ eng:"Atomic",tr:"atomal"});
medium.push({ eng:"Automatic",tr:"otomatik"});
medium.push({ eng:"Available",tr:"mevcut"});
medium.push({ eng:"Bad",tr:"kötü"});
medium.push({ eng:"Basic",tr:"temel"});
medium.push({ eng:"Beautiful",tr:"güzel"});
medium.push({ eng:"Beneficial",tr:"faydalı"});
medium.push({ eng:"Best",tr:"en iyi"});
medium.push({ eng:"Big",tr:"büyük"});
medium.push({ eng:"Black",tr:"siyah"});
medium.push({ eng:"Blind",tr:"kör"});
medium.push({ eng:"Blue",tr:"mavi"});
medium.push({ eng:"Both",tr:"her ikiside"});
medium.push({ eng:"Brief",tr:"özet/kısa"});
medium.push({ eng:"Bright",tr:"parlak"});
medium.push({ eng:"Broad",tr:"geniş"});
medium.push({ eng:"Brown",tr:"kahverengi"});
medium.push({ eng:"Busy",tr:"yoğun"});
medium.push({ eng:"Capable",tr:"yetenekli"});
medium.push({ eng:"Careful",tr:"dikkatli"});
medium.push({ eng:"Careless",tr:"dikkatsiz"});
medium.push({ eng:"Cautious",tr:"dikkatli/önemli"});
medium.push({ eng:"Central",tr:"merkezi"});
medium.push({ eng:"Ceramic",tr:"seramik"});
medium.push({ eng:"Certain",tr:"belirli"});
medium.push({ eng:"Cheap",tr:"ucuz"});
medium.push({ eng:"Civil",tr:"sivil"});
medium.push({ eng:"Clean",tr:"temiz"});
medium.push({ eng:"Clear",tr:"açık/anlaşılır"});
medium.push({ eng:"Cold",tr:"soğuk"});
medium.push({ eng:"Colorless",tr:"reknsiz"});
medium.push({ eng:"Comfortable",tr:"rahat"});
medium.push({ eng:"Common",tr:"yaygın"});
medium.push({ eng:"Compact",tr:"yoğun"});
medium.push({ eng:"Complete",tr:"tamamlanmış"});
medium.push({ eng:"Complex",tr:"karışık"});
medium.push({ eng:"Composite",tr:"karma"});
medium.push({ eng:"Compound",tr:"bileşim"});
medium.push({ eng:"Comprehensive",tr:"ayrıntılı"});
medium.push({ eng:"Confidential",tr:"gizli"});
medium.push({ eng:"Conscious",tr:"bilinçli"});
medium.push({ eng:"Considerable",tr:"hatırı sayılır/önemli"});
medium.push({ eng:"Constant",tr:"sabit"});
medium.push({ eng:"Constructive",tr:"yapıcı"});
medium.push({ eng:"Consumable",tr:"tüketilebilir"});
medium.push({ eng:"Continuous",tr:"sürekli"});
medium.push({ eng:"Cool",tr:"serin"});
medium.push({ eng:"Correct",tr:"doğru"});
medium.push({ eng:"Corrective",tr:"düzeltici"});
medium.push({ eng:"Counterclockwise",tr:"saat yönünün tersine"});
medium.push({ eng:"Critical",tr:"eleştirel"});
medium.push({ eng:"Cruel",tr:"kaba"});
medium.push({ eng:"Current",tr:"mevcut"});
medium.push({ eng:"Daily",tr:"günlük"});
medium.push({ eng:"Dangerous",tr:"tehlikeli"});
medium.push({ eng:"Dark",tr:"karanlık"});
medium.push({ eng:"Dead",tr:"ölü"});
medium.push({ eng:"Deaf",tr:"sağır"});
medium.push({ eng:"Dear",tr:"sevgili"});
medium.push({ eng:"Deep",tr:"derin"});
medium.push({ eng:"Definite",tr:"belirli/açık"});
medium.push({ eng:"Delicate",tr:"narin"});
medium.push({ eng:"Dental",tr:"dişlerle ilgili"});
medium.push({ eng:"Dependent",tr:"bağımlı"});
medium.push({ eng:"Destructive",tr:"yıkıcı"});
medium.push({ eng:"Different",tr:"farklı"});
medium.push({ eng:"Difficult",tr:"zor"});
medium.push({ eng:"Digital",tr:"dijital"});
medium.push({ eng:"Dim",tr:"loş"});
medium.push({ eng:"Dirty",tr:"kirli"});
medium.push({ eng:"Disciplinary",tr:"disiplinci"});
medium.push({ eng:"Diseased",tr:"hastalıklı"});
medium.push({ eng:"Dry",tr:"kuru"});
medium.push({ eng:"Due",tr:"hak edilen"});
medium.push({ eng:"Dull",tr:"sıkıcı"});
medium.push({ eng:"Dumb",tr:"aptal"});
medium.push({ eng:"Dynamic",tr:"dinamik"});
medium.push({ eng:"Each",tr:"her"});
medium.push({ eng:"Easy",tr:"kolay"});
medium.push({ eng:"Economic",tr:"iktisadi"});
medium.push({ eng:"Effective",tr:"etkili"});
medium.push({ eng:"Efficient",tr:"verimli"});
medium.push({ eng:"Eighth",tr:"sekizinci"});
medium.push({ eng:"Elastic",tr:"esnek"});
medium.push({ eng:"Electric",tr:"elektrikle ilgili"});
medium.push({ eng:"Electronic",tr:"elektronik"});
medium.push({ eng:"Else",tr:"başka"});
medium.push({ eng:"Empty",tr:"boş"});
medium.push({ eng:"Enough",tr:"yeterli"});
medium.push({ eng:"Entire",tr:"tüm"});
medium.push({ eng:"Environmental",tr:"çevresel"});
medium.push({ eng:"Equal",tr:"eşit"});
medium.push({ eng:"Essential",tr:"gerekli"});
medium.push({ eng:"Eventual",tr:"sonunda olan"});
medium.push({ eng:"Evident",tr:"besbelli"});
medium.push({ eng:"Exact",tr:"tam"});
medium.push({ eng:"Excellent",tr:"mükemmel"});
medium.push({ eng:"Excessive",tr:"aşırı"});
medium.push({ eng:"Explosive",tr:"patlayıcı"});
medium.push({ eng:"External",tr:"harici"});
medium.push({ eng:"Extra",tr:"ekstra"});
medium.push({ eng:"Extreme",tr:"aşırı"});
medium.push({ eng:"Faint",tr:"güçsüz"});
medium.push({ eng:"Fair",tr:"adil"});
medium.push({ eng:"False",tr:"yanlış"});
medium.push({ eng:"Familiar",tr:"aşina"});
medium.push({ eng:"Faraway",tr:"uzak"});
medium.push({ eng:"Fast",tr:"hızlı"});
medium.push({ eng:"Fat",tr:"şişman"});
medium.push({ eng:"Feeble",tr:"güçsüz"});
medium.push({ eng:"Fertile",tr:"bereketli"});
medium.push({ eng:"Few",tr:"az"});
medium.push({ eng:"Fifth",tr:"beşinci"});
medium.push({ eng:"Final",tr:"son"});
medium.push({ eng:"Financial",tr:"mali"});
medium.push({ eng:"Fine",tr:"iyi"});
medium.push({ eng:"Firm",tr:"sağlam"});
medium.push({ eng:"First",tr:"birinci"});
medium.push({ eng:"Fit",tr:"uygun"});
medium.push({ eng:"Flat",tr:"düz"});
medium.push({ eng:"Flexible",tr:"esnek"});
medium.push({ eng:"Foggy",tr:"sisli"});
medium.push({ eng:"Foolish",tr:"budalaca"});
medium.push({ eng:"Foreign",tr:"yabancı"});
medium.push({ eng:"Formal",tr:"resmi"});
medium.push({ eng:"Former",tr:"önceki"});
medium.push({ eng:"Fourth",tr:"dördüncü"});
medium.push({ eng:"Free",tr:"serbest"});
medium.push({ eng:"Frequent",tr:"sık"});
medium.push({ eng:"Fresh",tr:"taze"});
medium.push({ eng:"Full",tr:"dolu"});
medium.push({ eng:"Functional",tr:"fonksiyonel"});
medium.push({ eng:"Further",tr:"daha uzak"});
medium.push({ eng:"General",tr:"genel"});
medium.push({ eng:"Gentle",tr:"nazik"});
medium.push({ eng:"Good",tr:"iyi"});
medium.push({ eng:"Grand",tr:"büyük"});
medium.push({ eng:"Graphic",tr:"çizgesel"});
medium.push({ eng:"Grave",tr:"ciddi"});
medium.push({ eng:"Great",tr:"mükemmel"});
medium.push({ eng:"Green",tr:"yeşil"});
medium.push({ eng:"Happy",tr:"mutlu"});
medium.push({ eng:"Hard",tr:"zor"});
medium.push({ eng:"Harmful",tr:"zararlı"});
medium.push({ eng:"Hasty",tr:"aceleye gelmiş"});
medium.push({ eng:"Hazardous",tr:"tehlikeli"});
medium.push({ eng:"Healthy",tr:"sağlıklı"});
medium.push({ eng:"Heavy",tr:"ağır"});
medium.push({ eng:"Helpful",tr:"yardımsever"});
medium.push({ eng:"High",tr:"yüksek"});
medium.push({ eng:"Hilly",tr:"tepelik"});
medium.push({ eng:"Hind",tr:"arka"});
medium.push({ eng:"Hot",tr:"sıcak"});
medium.push({ eng:"Huge",tr:"çok büyük"});
medium.push({ eng:"Icy",tr:"buzlu"});
medium.push({ eng:"Idle",tr:"sonuçsuz"});
medium.push({ eng:"Ill",tr:"hasta"});
medium.push({ eng:"Immediate",tr:"acele"});
medium.push({ eng:"Imminent",tr:"yakın"});
medium.push({ eng:"Important",tr:"önemli"});
medium.push({ eng:"Improper",tr:"uygunsuz"});
medium.push({ eng:"Independent",tr:"bağımsız"});
medium.push({ eng:"Individual",tr:"bireysel"});
medium.push({ eng:"Inner",tr:"iç"});
medium.push({ eng:"Instant",tr:"hemen olan"});
medium.push({ eng:"Intense",tr:"şiddetli"});
medium.push({ eng:"Intermediate",tr:"ara"});
medium.push({ eng:"Internal",tr:"dahili"});
medium.push({ eng:"International",tr:"uluslararası"});
medium.push({ eng:"Junior",tr:"yaşça küçük"});
medium.push({ eng:"Keen",tr:"hevesli"});
medium.push({ eng:"Kind",tr:"nazik"});
medium.push({ eng:"Large",tr:"geniş"});
medium.push({ eng:"Last",tr:"son"});
medium.push({ eng:"Late",tr:"geç"});
medium.push({ eng:"Lateral",tr:"yanal"});
medium.push({ eng:"Latest",tr:"en son"});
medium.push({ eng:"Latter",tr:"sonraki"});
medium.push({ eng:"Lawful",tr:"yasalara uygun"});
medium.push({ eng:"Lazy",tr:"tembel"});
medium.push({ eng:"Leaky",tr:"sızıntılı"});
medium.push({ eng:"Lean",tr:"yağsız"});
medium.push({ eng:"Least",tr:"en az"});
medium.push({ eng:"Legal",tr:"yasal"});
medium.push({ eng:"Less",tr:"daha az"});
medium.push({ eng:"Lethal",tr:"öldürücü"});
medium.push({ eng:"Level",tr:"düz"});
medium.push({ eng:"Likely",tr:"muhtemel"});
medium.push({ eng:"Liquid",tr:"sıvı"});
medium.push({ eng:"Little",tr:"az"});
medium.push({ eng:"Lively",tr:"hayat dolu"});
medium.push({ eng:"Local",tr:"bölgesel"});
medium.push({ eng:"Lone",tr:"kimsesiz"});
medium.push({ eng:"Long",tr:"uzun"});
medium.push({ eng:"Loose",tr:"gevşek"});
medium.push({ eng:"looser"});
medium.push({ eng:"loud",tr:"yüksek sesli"});
medium.push({ eng:"low",tr:"alçak"});
medium.push({ eng:"main",tr:"asıl"});
medium.push({ eng:"many",tr:"çok"});
medium.push({ eng:"mean",tr:"cimri"});
medium.push({ eng:"mechanical",tr:"mekanik"});
medium.push({ eng:"medical",tr:"tıbbi"});
medium.push({ eng:"mental",tr:"zihinsel"});
medium.push({ eng:" "});
medium.push({ eng:"  "});
medium.push({ eng:"mere",tr:"sırf"});
medium.push({ eng:"metallic",tr:"metalik"});
medium.push({ eng:"middle",tr:"orta"});
medium.push({ eng:"minor",tr:"önemsiz"});
medium.push({ eng:"minus",tr:"eksi"});
medium.push({ eng:"miscellaneous",tr:"çeşitli"});
medium.push({ eng:"misty",tr:"sisli"});
medium.push({ eng:"mobile",tr:"seyyar"});
medium.push({ eng:"modern",tr:"modern"});
medium.push({ eng:"modular",tr:"modüler"});
medium.push({ eng:"moral",tr:"ahlaklı"});
medium.push({ eng:"more",tr:"daha çok"});
medium.push({ eng:"most",tr:"en çok"});
medium.push({ eng:"movable",tr:"hareket edebilen"});
medium.push({ eng:"muddy",tr:"çamurlu"});
medium.push({ eng:"multiple",tr:"çeşitli"});
medium.push({ eng:"naked",tr:"çıplak"});
medium.push({ eng:"narcotic",tr:"narkotik"});
medium.push({ eng:"narrow",tr:"dar"});
medium.push({ eng:"national",tr:"milli"});
medium.push({ eng:"natural",tr:"doğal"});
medium.push({ eng:"neat",tr:"düzenli"});
medium.push({ eng:"necessary",tr:"gerekli"});
medium.push({ eng:"negative",tr:"olumsuz"});
medium.push({ eng:"nervous",tr:"sinirli"});
medium.push({ eng:"neutral",tr:"nötr"});
medium.push({ eng:"new",tr:"yeni"});
medium.push({ eng:"next",tr:"sonraki"});
medium.push({ eng:"nice",tr:"hoş"});
medium.push({ eng:"noisy",tr:"gürültülü"});
medium.push({ eng:"nominal",tr:"nominal"});
medium.push({ eng:"normal",tr:"mormal"});
medium.push({ eng:"nuclear",tr:"nükleer"});
medium.push({ eng:"numeric",tr:"sayısal"});
medium.push({ eng:"numerous",tr:"çeşitli"});
medium.push({ eng:"obvious",tr:"aşikar"});
medium.push({ eng:"occasional",tr:"arada bir olan"});
medium.push({ eng:"odd",tr:"garip"});
medium.push({ eng:"old",tr:"yaşlı/eski"});
medium.push({ eng:"open",tr:"açık"});
medium.push({ eng:"operational",tr:"kullanıma hazır"});
medium.push({ eng:"opposite",tr:"zıt"});
medium.push({ eng:"optional",tr:"tercihe bağlı"});
medium.push({ eng:"oral",tr:"sözel"});
medium.push({ eng:"ordinary",tr:"sıradan"});
medium.push({ eng:"organizational",tr:"örgütsel"});
medium.push({ eng:"original",tr:"orijinal"});
medium.push({ eng:"other",tr:"diğer"});
medium.push({ eng:"outside",tr:"dış"});
medium.push({ eng:"own",tr:"kendisinin"});
medium.push({ eng:"pale",tr:"solgun"});
medium.push({ eng:"parallel",tr:"paralel"});
medium.push({ eng:"particular",tr:"belirli"});
medium.push({ eng:"passive",tr:"pasif"});
medium.push({ eng:"past",tr:"geçmiş"});
medium.push({ eng:"periodic",tr:"periyodik"});
medium.push({ eng:"permanent",tr:"sürekli"});
medium.push({ eng:"personal",tr:"kişisel"});
medium.push({ eng:"physical",tr:"fiziksel"});
medium.push({ eng:"plain",tr:"sade"});
medium.push({ eng:"plenty",tr:"bol miktar"});
medium.push({ eng:"poisonous",tr:"zehirli"});
medium.push({ eng:"polite",tr:"nazik"});
medium.push({ eng:"political",tr:"siyasi"});
medium.push({ eng:"poor",tr:"fakir/zavallı"});
medium.push({ eng:"portable",tr:"portatif"});
medium.push({ eng:"positive",tr:"olumlu"});
medium.push({ eng:"possible",tr:"mümkün"});
medium.push({ eng:"potential",tr:"potansiyel"});
medium.push({ eng:"powerful",tr:"güçlü"});
medium.push({ eng:"practical",tr:"pratik"});
medium.push({ eng:"pretty",tr:"hoş/çekici"});
medium.push({ eng:"previous",tr:"önceki"});
medium.push({ eng:"primary",tr:"baş/temel"});
medium.push({ eng:"prior",tr:"önceki/öncelikli"});
medium.push({ eng:"private",tr:"özel"});
medium.push({ eng:"probable",tr:"muhtemel"});
medium.push({ eng:"productive",tr:"verimli"});
medium.push({ eng:"professional",tr:"profesyonel"});
medium.push({ eng:"programmable",tr:"programlanabilir"});
medium.push({ eng:"proper",tr:"münasip"});
medium.push({ eng:"protective",tr:"koruyucu"});
medium.push({ eng:"pure",tr:"katıksız"});
medium.push({ eng:"purple",tr:"mor"});
medium.push({ eng:"quick",tr:"hızlı"});
medium.push({ eng:"radioactive",tr:"radyoaktif"});
medium.push({ eng:"random",tr:"düzensiz"});
medium.push({ eng:"rapid",tr:"hızlı"});
medium.push({ eng:"raw",tr:"ham/çiğ"});
medium.push({ eng:"ready",tr:"hazır"});
medium.push({ eng:"real",tr:"gerçek"});
medium.push({ eng:"rectangular",tr:"dikdörtgen biçiminde "});
medium.push({ eng:"red",tr:"kırmızı"});
medium.push({ eng:"regional",tr:"bölgesel"});
medium.push({ eng:"regular",tr:"düzenli"});
medium.push({ eng:"reliable",tr:"güvenilir"});
medium.push({ eng:"remote",tr:"uzak"});
medium.push({ eng:"respective",tr:"kendi/kişisel"});
medium.push({ eng:"responsible",tr:"sorumlu"});
medium.push({ eng:"retail",tr:"perakende"});
medium.push({ eng:"reusable",tr:"tekrar kullanılabilir"});
medium.push({ eng:"rich",tr:"zengin"});
medium.push({ eng:"right",tr:"doğru/sağ"});
medium.push({ eng:"rigid",tr:"sert/eğilmez"});
medium.push({ eng:"ripe",tr:"olgun"});
medium.push({ eng:"rough",tr:"pürüzlü/kaba"});
medium.push({ eng:"sad",tr:"üzgün"});
medium.push({ eng:"safe",tr:"güvenli"});
medium.push({ eng:"same",tr:"aynı"});
medium.push({ eng:"satisfactory",tr:"hoşnut edici"});
medium.push({ eng:"schematic",tr:"şematik"});
medium.push({ eng:"secondary",tr:"ikincil"});
medium.push({ eng:"secure",tr:"güvenli"});
medium.push({ eng:"senior",tr:"kıdemli"});
medium.push({ eng:"sensitive",tr:"hassas"});
medium.push({ eng:"separate",tr:"ayrı"});
medium.push({ eng:"sequential",tr:"ardışık"});
medium.push({ eng:"serious",tr:"ciddi"});
medium.push({ eng:"seventh",tr:"yedinci"});
medium.push({ eng:"several",tr:"çeşitli"});
medium.push({ eng:"severe",tr:"sert/şiddetli"});
medium.push({ eng:"shady",tr:"gölgeli"});
medium.push({ eng:"shallow",tr:"sığ/yüzeysel"});
medium.push({ eng:"sharp",tr:"keskin"});
medium.push({ eng:"shy",tr:"utangaç"});
medium.push({ eng:"shiny",tr:"parlak"});
medium.push({ eng:"short",tr:"kısa"});
medium.push({ eng:"sick",tr:"hasta"});
medium.push({ eng:"significant",tr:"önemli"});
medium.push({ eng:"silent",tr:"sessiz"});
medium.push({ eng:"similar",tr:"benzer"});
medium.push({ eng:"simple",tr:"basit"});
medium.push({ eng:"simultaneous",tr:"eş zamanlı"});
medium.push({ eng:"single",tr:"tek/bekar"});
medium.push({ eng:"sixth",tr:"altıncı"});
medium.push({ eng:"slack",tr:"gevşek"});
medium.push({ eng:"slight",tr:"ince/narin"});
medium.push({ eng:"slippery",tr:"kaygan"});
medium.push({ eng:"small",tr:"küçük"});
medium.push({ eng:"smart",tr:"zarif/gösterişli"});
medium.push({ eng:"smooth",tr:"düz/akıcı"});
medium.push({ eng:"social",tr:"sosyal"});
medium.push({ eng:"soft",tr:"yumuşak"});
medium.push({ eng:"solar",tr:"güneşle ilgili"});
medium.push({ eng:"solid",tr:"katı"});
medium.push({ eng:"some",tr:"biraz"});
medium.push({ eng:"sour",tr:"ekşi"});
medium.push({ eng:"special",tr:"özel"});
medium.push({ eng:"specific",tr:"belirli"});
medium.push({ eng:"standby",tr:"yedek"});
medium.push({ eng:"static",tr:"statik"});
medium.push({ eng:"stationary",tr:"sabit"});
medium.push({ eng:"steady",tr:"sabit/sağlam"});
medium.push({ eng:"steep",tr:"dik/sarp"});
medium.push({ eng:"sterile",tr:"steril"});
medium.push({ eng:"sticky",tr:"yapışkan"});
medium.push({ eng:"stiff",tr:"katı/sert"});
medium.push({ eng:"still",tr:"durgun"});
medium.push({ eng:"straight",tr:"dümdüz"});
medium.push({ eng:"strange",tr:"acayip/tuhaf"});
medium.push({ eng:"stranger",tr:"yabancı"});
medium.push({ eng:"strategic",tr:"stratejik"});
medium.push({ eng:"strict",tr:"katı/sağlam"});
medium.push({ eng:"strong",tr:"güçlü"});
medium.push({ eng:"structural",tr:"yapısal"});
medium.push({ eng:"successful",tr:"başarılı"});
medium.push({ eng:"successive",tr:"ardıl"});
medium.push({ eng:"such",tr:"öylesine"});
medium.push({ eng:"sudden",tr:"ani"});
medium.push({ eng:"sufficient",tr:"yeterli"});
medium.push({ eng:"suitable",tr:"uygun"});
medium.push({ eng:"sunny",tr:"güneşli"});
medium.push({ eng:"sure",tr:"kesin"});
medium.push({ eng:"sweet",tr:"tatlı"});
medium.push({ eng:"swift",tr:"atik/tez"});
medium.push({ eng:"symbolic",tr:"sembolik"});
medium.push({ eng:"synthetic",tr:"sentetik"});
medium.push({ eng:"tactical",tr:"taktiksel"});
medium.push({ eng:"tall",tr:"uzun"});
medium.push({ eng:"taut",tr:"gergin"});
medium.push({ eng:"technical",tr:"teknik"});
medium.push({ eng:"temporary",tr:"geçici"});
medium.push({ eng:"terminal",tr:"ölümcül"});
medium.push({ eng:"thermal",tr:"termal"});
medium.push({ eng:"thick",tr:"kalın"});
medium.push({ eng:"third",tr:"üçüncü"});
medium.push({ eng:"thirsty",tr:"susamış"});
medium.push({ eng:"thorough",tr:"tam/eksiksiz"});
medium.push({ eng:"tight",tr:"dar"});
medium.push({ eng:"tiny",tr:"küçük/ufak"});
medium.push({ eng:"transparent",tr:"transparan"});
medium.push({ eng:"tropical",tr:"tropikal"});
medium.push({ eng:"true",tr:"doğru"});
medium.push({ eng:"typical",tr:"tipik"});
medium.push({ eng:"unique",tr:"eşsiz"});
medium.push({ eng:"universal",tr:"evrensel"});
medium.push({ eng:"upper",tr:"üstteki"});
medium.push({ eng:"urgent",tr:"acil"});
medium.push({ eng:"useful",tr:"faydalı"});
medium.push({ eng:"usual",tr:"olağan"});
medium.push({ eng:"valid",tr:"geçerli"});
medium.push({ eng:"valuable",tr:"değerli"});
medium.push({ eng:"variable",tr:"değişken"});
medium.push({ eng:"various",tr:"çeşitli"});
medium.push({ eng:"vertical",tr:"dikey"});
medium.push({ eng:"violent",tr:"şiddetli"});
medium.push({ eng:"virtual",tr:"gerçek/asıl"});
medium.push({ eng:"visible",tr:"görülebilir"});
medium.push({ eng:"visual",tr:"görsel"});
medium.push({ eng:"vital",tr:"önemli/hayati"});
medium.push({ eng:"warm",tr:"ılık"});
medium.push({ eng:"waterproof",tr:"su geçirmez"});
medium.push({ eng:"watertight",tr:"suya dayanıklı"});
medium.push({ eng:"weak",tr:"zayıf"});
medium.push({ eng:"weary",tr:"yorgun/usanmış"});
medium.push({ eng:"wet",tr:"ıslak"});
medium.push({ eng:"white",tr:"beyaz"});
medium.push({ eng:"whole",tr:"tüm"});
medium.push({ eng:"wide",tr:"geniş"});
medium.push({ eng:"wise",tr:"akıllı/mantıklı"});
medium.push({ eng:"wooden",tr:"tahta/ahşap"});
medium.push({ eng:"woolen",tr:"yün"});
medium.push({ eng:"wrong",tr:"yanlış"});
medium.push({ eng:"wrongful",tr:"haksız"});
medium.push({ eng:"yellow",tr:"sarı"});
medium.push({ eng:"yesterday",tr:"dün"});
medium.push({ eng:"young",tr:"genç"});
medium.push({ eng:"harmless",tr:"zararsız"});
medium.push({ eng:"inactive",tr:"hareketsiz/pasif"});
medium.push({ eng:"incomplete",tr:"tamamlanmamış"});
medium.push({ eng:"incorrect",tr:"yanlış"});
medium.push({ eng:"indirect",tr:"dolaylı "});


hard.push({ eng:"Able",tr:"güçlü"});
hard.push({ eng:"Abnormal",tr:"anormal"});
hard.push({ eng:"Absent",tr:"yok"});
hard.push({ eng:"Absolute",tr:"mükemmel/tam"});
hard.push({ eng:"Acceptable",tr:"makul"});
hard.push({ eng:"Accessible",tr:"ulaşılabilir"});
hard.push({ eng:"Accurate",tr:"kesin/tam"});
hard.push({ eng:"Acidic",tr:"asitlenmiş"});
hard.push({ eng:"Acoustic",tr:"akustik"});
hard.push({ eng:"Active",tr:"faal"});
hard.push({ eng:"Adaptable",tr:"uyarlanabilir"});
hard.push({ eng:"Additional",tr:"ilave/ek"});
hard.push({ eng:"Adequate",tr:"yeterli"});
hard.push({ eng:"Administrative",tr:"yönetimsel"});
hard.push({ eng:"Advantageous",tr:"avantajlı"});
hard.push({ eng:"Advisable",tr:"önerilen"});
hard.push({ eng:"Affirmative",tr:"olumlu"});
hard.push({ eng:"Ago",tr:"önce"});
hard.push({ eng:"Airborne",tr:"uçan"});
hard.push({ eng:"Airy",tr:"havalı"});
hard.push({ eng:"All",tr:"tüm"});
hard.push({ eng:"Alone",tr:"yalnız"});
hard.push({ eng:"Alphabetical",tr:"alfabetik"});
hard.push({ eng:"American",tr:"Amerikan"});
hard.push({ eng:"Amphibious",tr:"hırslı"});
hard.push({ eng:"Angry",tr:"kızgın"});
hard.push({ eng:"Annual",tr:"yıllık"});
hard.push({ eng:"Another",tr:"başka"});
hard.push({ eng:"Any",tr:"hiç"});
hard.push({ eng:"Apparent",tr:"anlaşılır/açık"});
hard.push({ eng:"Applicable",tr:"uygulanabilir"});
hard.push({ eng:"Appreciable",tr:"kayda değer"});
hard.push({ eng:"Appropriate",tr:"uygun"});
hard.push({ eng:"Artificial",tr:"yapay"});
hard.push({ eng:"Atomic",tr:"atomal"});
hard.push({ eng:"Audible",tr:"duyulabilir"});
hard.push({ eng:"Automatic",tr:"otomatik"});
hard.push({ eng:"Auxiliary",tr:"yardımcı"});
hard.push({ eng:"Available",tr:"mevcut"});
hard.push({ eng:"Bad",tr:"kötü"});
hard.push({ eng:"Ballistick",tr:"balistik"});
hard.push({ eng:"Bare",tr:"yalın"});
hard.push({ eng:"Barometric",tr:"barometrik"});
hard.push({ eng:"Basic",tr:"temel"});
hard.push({ eng:"Beautiful",tr:"güzel"});
hard.push({ eng:"Beneficial",tr:"faydalı"});
hard.push({ eng:"Best",tr:"en iyi"});
hard.push({ eng:"Big",tr:"büyük"});
hard.push({ eng:"Binary",tr:"çift"});
hard.push({ eng:"Biological",tr:"biyolojik"});
hard.push({ eng:"Bitter",tr:"acı"});
hard.push({ eng:"Black",tr:"siyah"});
hard.push({ eng:"Blind",tr:"kör"});
hard.push({ eng:"Blue",tr:"mavi"});
hard.push({ eng:"Both",tr:"her ikiside"});
hard.push({ eng:"Brief",tr:"özet/kısa"});
hard.push({ eng:"Bright",tr:"parlak"});
hard.push({ eng:"Broad",tr:"geniş"});
hard.push({ eng:"Brown",tr:"kahverengi"});
hard.push({ eng:"Busy",tr:"yoğun"});
hard.push({ eng:"Capable",tr:"yetenekli"});
hard.push({ eng:"Careful",tr:"dikkatli"});
hard.push({ eng:"Careless",tr:"dikkatsiz"});
hard.push({ eng:"Carnal",tr:"cinsel"});
hard.push({ eng:"Cautious",tr:"dikkatli/önemli"});
hard.push({ eng:"Celestial",tr:"gökle ilgili"});
hard.push({ eng:"Celsius",tr:"santigrat"});
hard.push({ eng:"Central",tr:"merkezi"});
hard.push({ eng:"Centrifugal",tr:"merkezkaç"});
hard.push({ eng:"Ceramic",tr:"seramik"});
hard.push({ eng:"Certain",tr:"belirli"});
hard.push({ eng:"Cheap",tr:"ucuz"});
hard.push({ eng:"Civil",tr:"sivil"});
hard.push({ eng:"Clean",tr:"temiz"});
hard.push({ eng:"Clear",tr:"açık/anlaşılır"});
hard.push({ eng:"Coarse",tr:"kaba"});
hard.push({ eng:"Cold",tr:"soğuk"});
hard.push({ eng:"Colorless",tr:"reknsiz"});
hard.push({ eng:"Comfortable",tr:"rahat"});
hard.push({ eng:"Commercial",tr:"ticari"});
hard.push({ eng:"Common",tr:"yaygın"});
hard.push({ eng:"Compact",tr:"yoğun"});
hard.push({ eng:"Complete",tr:"tamamlanmış"});
hard.push({ eng:"Complex",tr:"karışık"});
hard.push({ eng:"Composite",tr:"karma"});
hard.push({ eng:"Compound",tr:"bileşim"});
hard.push({ eng:"Comprehensive",tr:"ayrıntılı"});
hard.push({ eng:"Compulsory",tr:"mecburi"});
hard.push({ eng:"Concrete",tr:"somut"});
hard.push({ eng:"Concurrent",tr:"tesadüfi"});
hard.push({ eng:"Confidential",tr:"gizli"});
hard.push({ eng:"Conscious",tr:"bilinçli"});
hard.push({ eng:"Consecutive",tr:"ardışık"});
hard.push({ eng:"Considerable",tr:"hatırı sayılır/önemli"});
hard.push({ eng:"Constant",tr:"sabit"});
hard.push({ eng:"Constructive",tr:"yapıcı"});
hard.push({ eng:"Consumable",tr:"tüketilebilir"});
hard.push({ eng:"Continuous",tr:"sürekli"});
hard.push({ eng:"Convalescent",tr:"iyileşen"});
hard.push({ eng:"Convenient",tr:"uygun"});
hard.push({ eng:"Conventional",tr:"konsansiyonel"});
hard.push({ eng:"Cool",tr:"serin"});
hard.push({ eng:"Cooperative",tr:"yardımcı"});
hard.push({ eng:"Coordinating",tr:"eşgüdümlü"});
hard.push({ eng:"Correct",tr:"doğru"});
hard.push({ eng:"Corrective",tr:"düzeltici"});
hard.push({ eng:"Counterclockwise",tr:"saat yönünün tersine"});
hard.push({ eng:"Critical",tr:"eleştirel"});
hard.push({ eng:"Cruel",tr:"kaba"});
hard.push({ eng:"Cryptographic",tr:"kriptografik"});
hard.push({ eng:"Cubic",tr:"kübik"});
hard.push({ eng:"Culpable",tr:"suçlanmayı hakeden"});
hard.push({ eng:"Current",tr:"mevcut"});
hard.push({ eng:"Daily",tr:"günlük"});
hard.push({ eng:"Dangerous",tr:"tehlikeli"});
hard.push({ eng:"Dark",tr:"karanlık"});
hard.push({ eng:"Dead",tr:"ölü"});
hard.push({ eng:"Deaf",tr:"sağır"});
hard.push({ eng:"Dear",tr:"sevgili"});
hard.push({ eng:"Decimal",tr:"ondalık"});
hard.push({ eng:"Deep",tr:"derin"});
hard.push({ eng:"Defective",tr:"kusurlu"});
hard.push({ eng:"Definite",tr:"belirli/açık"});
hard.push({ eng:"Delicate",tr:"narin"});
hard.push({ eng:"Demonstrable",tr:"kanıtlanabilir"});
hard.push({ eng:"Dental",tr:"dişlerle ilgili"});
hard.push({ eng:"Dependent",tr:"bağımlı"});
hard.push({ eng:"Destructive",tr:"yıkıcı"});
hard.push({ eng:"Diagnostic",tr:"teşhis edilebilir"});
hard.push({ eng:"Diagonal",tr:"köşegen"});
hard.push({ eng:"Different",tr:"farklı"});
hard.push({ eng:"Differential",tr:"ücret farkı"});
hard.push({ eng:"Difficult",tr:"zor"});
hard.push({ eng:"Digital",tr:"dijital"});
hard.push({ eng:"Dim",tr:"loş"});
hard.push({ eng:"Dirty",tr:"kirli"});
hard.push({ eng:"Disciplinary",tr:"disiplinci"});
hard.push({ eng:"Diseased",tr:"hastalıklı"});
hard.push({ eng:"Dishonorable",tr:"onursuzca"});
hard.push({ eng:"Distinct",tr:"farklı/belirgin"});
hard.push({ eng:"Ditty",tr:"kısa ve basit şarkı"});
hard.push({ eng:"Dormant",tr:"hareketsiz"});
hard.push({ eng:"Double",tr:"çift"});
hard.push({ eng:"Drafty",tr:"soğuk cereyanlı"});
hard.push({ eng:"Dry",tr:"kuru"});
hard.push({ eng:"Drowsy",tr:"uykulu"});
hard.push({ eng:"Dual",tr:"ikili"});
hard.push({ eng:"Due",tr:"hak edilen"});
hard.push({ eng:"Dull",tr:"sıkıcı"});
hard.push({ eng:"Dumb",tr:"aptal"});
hard.push({ eng:"Dynamic",tr:"dinamik"});
hard.push({ eng:"Each",tr:"her"});
hard.push({ eng:"Easy",tr:"kolay"});
hard.push({ eng:"Economic",tr:"iktisadi"});
hard.push({ eng:"Educational",tr:"hesaplı"});
hard.push({ eng:"Effective",tr:"etkili"});
hard.push({ eng:"Efficient",tr:"verimli"});
hard.push({ eng:"Eighth",tr:"sekizinci"});
hard.push({ eng:"Elastic",tr:"esnek"});
hard.push({ eng:"Electric",tr:"elektrikle ilgili"});
hard.push({ eng:"Electronic",tr:"elektronik"});
hard.push({ eng:"Eligible",tr:"haklı"});
hard.push({ eng:"Else",tr:"başka"});
hard.push({ eng:"Empty",tr:"boş"});
hard.push({ eng:"Enough",tr:"yeterli"});
hard.push({ eng:"Entire",tr:"tüm"});
hard.push({ eng:"Environmental",tr:"çevresel"});
hard.push({ eng:"Equal",tr:"eşit"});
hard.push({ eng:"Erect",tr:"dimdik"});
hard.push({ eng:"Erratic",tr:"düzensiz"});
hard.push({ eng:"Essential",tr:"gerekli"});
hard.push({ eng:"Eventual",tr:"sonunda olan"});
hard.push({ eng:"Every",tr:"her"});
hard.push({ eng:"Evident",tr:"besbelli"});
hard.push({ eng:"Exact",tr:"tam"});
hard.push({ eng:"Excellent",tr:"mükemmel"});
hard.push({ eng:"Excessive",tr:"aşırı"});
hard.push({ eng:"Exclusive",tr:"paylaşılmayan"});
hard.push({ eng:"Explosive",tr:"patlayıcı"});
hard.push({ eng:"Extensive",tr:"kapsamlı"});
hard.push({ eng:"External",tr:"harici"});
hard.push({ eng:"Extra",tr:"ekstra"});
hard.push({ eng:"Extreme",tr:"aşırı"});
hard.push({ eng:"Faint",tr:"güçsüz"});
hard.push({ eng:"Fair",tr:"adil"});
hard.push({ eng:"False",tr:"yanlış"});
hard.push({ eng:"Familiar",tr:"aşina"});
hard.push({ eng:"Faraway",tr:"uzak"});
hard.push({ eng:"Fast",tr:"hızlı"});
hard.push({ eng:"Fat",tr:"şişman"});
hard.push({ eng:"Fatal",tr:"ölümcül"});
hard.push({ eng:"Faulty",tr:"hatalı"});
hard.push({ eng:"Feasible",tr:"yapılabilir"});
hard.push({ eng:"Federal",tr:"federal"});
hard.push({ eng:"Feeble",tr:"güçsüz"});
hard.push({ eng:"Fertile",tr:"bereketli"});
hard.push({ eng:"Few",tr:"az"});
hard.push({ eng:"Fifth",tr:"beşinci"});
hard.push({ eng:"Final",tr:"son"});
hard.push({ eng:"Financial",tr:"mali"});
hard.push({ eng:"Fine",tr:"iyi"});
hard.push({ eng:"Firm",tr:"sağlam"});
hard.push({ eng:"First",tr:"birinci"});
hard.push({ eng:"Fiscal",tr:"mali"});
hard.push({ eng:"Fit",tr:"uygun"});
hard.push({ eng:"Flammable",tr:"kolay tutuşur"});
hard.push({ eng:"Flat",tr:"düz"});
hard.push({ eng:"Flexible",tr:"esnek"});
hard.push({ eng:"Foggy",tr:"sisli"});
hard.push({ eng:"Foolish",tr:"budalaca"});
hard.push({ eng:"Foreign",tr:"yabancı"});
hard.push({ eng:"Formal",tr:"resmi"});
hard.push({ eng:"Former",tr:"önceki"});
hard.push({ eng:"Fourth",tr:"dördüncü"});
hard.push({ eng:"Free",tr:"serbest"});
hard.push({ eng:"Frequent",tr:"sık"});
hard.push({ eng:"Fresh",tr:"taze"});
hard.push({ eng:"Full",tr:"dolu"});
hard.push({ eng:"Functional",tr:"fonksiyonel"});
hard.push({ eng:"Fundamental",tr:"en gerekli"});
hard.push({ eng:"Further",tr:"daha uzak"});
hard.push({ eng:"General",tr:"genel"});
hard.push({ eng:"Gentle",tr:"nazik"});
hard.push({ eng:"Good",tr:"iyi"});
hard.push({ eng:"Gradual",tr:"kademeli"});
hard.push({ eng:"Grand",tr:"büyük"});
hard.push({ eng:"Graphic",tr:"çizgesel"});
hard.push({ eng:"Grave",tr:"ciddi"});
hard.push({ eng:"Great",tr:"mükemmel"});
hard.push({ eng:"Green",tr:"yeşil"});
hard.push({ eng:"Grievous",tr:"acı veren"});
hard.push({ eng:"Happy",tr:"mutlu"});
hard.push({ eng:"Hard",tr:"zor"});
hard.push({ eng:"Harmful",tr:"zararlı"});
hard.push({ eng:"Hasty",tr:"aceleye gelmiş"});
hard.push({ eng:"Hazardous",tr:"tehlikeli"});
hard.push({ eng:"Healthy",tr:"sağlıklı"});
hard.push({ eng:"Heavy",tr:"ağır"});
hard.push({ eng:"Helpful",tr:"yardımsever"});
hard.push({ eng:"High",tr:"yüksek"});
hard.push({ eng:"Hilly",tr:"tepelik"});
hard.push({ eng:"Hind",tr:"arka"});
hard.push({ eng:"Hollow",tr:"oyuk"});
hard.push({ eng:"Honorable",tr:"onursal"});
hard.push({ eng:"Horizontal",tr:"yatay"});
hard.push({ eng:"Hot",tr:"sıcak"});
hard.push({ eng:"Huge",tr:"çok büyük"});
hard.push({ eng:"Hydraulic",tr:"hidrolik"});
hard.push({ eng:"Icy",tr:"buzlu"});
hard.push({ eng:"Identical",tr:"hemen hemen aynı"});
hard.push({ eng:"Idle",tr:"sonuçsuz"});
hard.push({ eng:"Ill",tr:"hasta"});
hard.push({ eng:"Immediate",tr:"acele"});
hard.push({ eng:"Imminent",tr:"yakın"});
hard.push({ eng:"Important",tr:"önemli"});
hard.push({ eng:"Improper",tr:"uygunsuz"});
hard.push({ eng:"Inclusive",tr:"herşey dahil"});
hard.push({ eng:"Independent",tr:"bağımsız"});
hard.push({ eng:"Indicative",tr:"belirtici"});
hard.push({ eng:"Individual",tr:"bireysel"});
hard.push({ eng:"Inertia",tr:"atalet"});
hard.push({ eng:"Inherent",tr:"doğasında olan"});
hard.push({ eng:"Inner",tr:"iç"});
hard.push({ eng:"Instant",tr:"hemen olan"});
hard.push({ eng:"Instantaneous",tr:"anlık"});
hard.push({ eng:"Intense",tr:"şiddetli"});
hard.push({ eng:"Interchangeable",tr:"birbirinin yerine geçebilir"});
hard.push({ eng:"Intermediate",tr:"ara"});
hard.push({ eng:"Internal",tr:"dahili"});
hard.push({ eng:"International",tr:"uluslararası"});
hard.push({ eng:"Intrinsic",tr:"esas"});
hard.push({ eng:"Junior",tr:"yaşça küçük"});
hard.push({ eng:"Keen",tr:"hevesli"});
hard.push({ eng:"Kind",tr:"nazik"});
hard.push({ eng:"Large",tr:"geniş"});
hard.push({ eng:"Last",tr:"son"});
hard.push({ eng:"Late",tr:"geç"});
hard.push({ eng:"Lateral",tr:"yanal"});
hard.push({ eng:"Latest",tr:"en son"});
hard.push({ eng:"Latter",tr:"sonraki"});
hard.push({ eng:"Lawful",tr:"yasalara uygun"});
hard.push({ eng:"Lazy",tr:"tembel"});
hard.push({ eng:"Leaky",tr:"sızıntılı"});
hard.push({ eng:"Lean",tr:"yağsız"});
hard.push({ eng:"Least",tr:"en az"});
hard.push({ eng:"Legal",tr:"yasal"});
hard.push({ eng:"Lengthy",tr:"upuzun"});
hard.push({ eng:"Less",tr:"daha az"});
hard.push({ eng:"Lethal",tr:"öldürücü"});
hard.push({ eng:"Level",tr:"düz"});
hard.push({ eng:"Likely",tr:"muhtemel"});
hard.push({ eng:"Linear",tr:"doğrusal"});
hard.push({ eng:"Liquid",tr:"sıvı"});
hard.push({ eng:"Literal",tr:"kelimesi kelimesine"});
hard.push({ eng:"Little",tr:"az"});
hard.push({ eng:"Lively",tr:"hayat dolu"});
hard.push({ eng:"Local",tr:"bölgesel"});
hard.push({ eng:"Lone",tr:"kimsesiz"});
hard.push({ eng:"Long",tr:"uzun"});
hard.push({ eng:"Loose",tr:"gevşek"});
hard.push({ eng:"looser"});
hard.push({ eng:"loud",tr:"yüksek sesli"});
hard.push({ eng:"low",tr:"alçak"});
hard.push({ eng:"magnetic",tr:"manyetik"});
hard.push({ eng:"main",tr:"asıl"});
hard.push({ eng:"mandatory",tr:"zorunlu"});
hard.push({ eng:"manifold",tr:"türlü türlü"});
hard.push({ eng:"many",tr:"çok"});
hard.push({ eng:"marginal",tr:"marjinal"});
hard.push({ eng:"marine",tr:"bahriyeli"});
hard.push({ eng:"martial",tr:"savaşla ilgili"});
hard.push({ eng:" "});
hard.push({ eng:"  "});
hard.push({ eng:"mean",tr:"cimri"});
hard.push({ eng:"mechanical",tr:"mekanik"});
hard.push({ eng:"medical",tr:"tıbbi"});
hard.push({ eng:"mental",tr:"zihinsel"});
hard.push({ eng:"mere",tr:"sırf"});
hard.push({ eng:"metallic",tr:"metalik"});
hard.push({ eng:"middle",tr:"orta"});
hard.push({ eng:"minor",tr:"önemsiz"});
hard.push({ eng:"minus",tr:"eksi"});
hard.push({ eng:"miscellaneous",tr:"çeşitli"});
hard.push({ eng:"misty",tr:"sisli"});
hard.push({ eng:"mnemonic",tr:"bellekle ilgili"});
hard.push({ eng:"mobile",tr:"seyyar"});
hard.push({ eng:"modern",tr:"modern"});
hard.push({ eng:"modifiable",tr:"değiştirilebilen"});
hard.push({ eng:"modular",tr:"modüler"});
hard.push({ eng:"molten",tr:"dökme"});
hard.push({ eng:"momentary",tr:"bir anlık"});
hard.push({ eng:"moral",tr:"ahlaklı"});
hard.push({ eng:"more",tr:"daha çok"});
hard.push({ eng:"most",tr:"en çok"});
hard.push({ eng:"movable",tr:"hareket edebilen"});
hard.push({ eng:"muddy",tr:"çamurlu"});
hard.push({ eng:"multiple",tr:"çeşitli"});
hard.push({ eng:"mutual",tr:"karşılıklı"});
hard.push({ eng:"mythological",tr:"mitolojik"});
hard.push({ eng:"naked",tr:"çıplak"});
hard.push({ eng:"narcotic",tr:"narkotik"});
hard.push({ eng:"narrow",tr:"dar"});
hard.push({ eng:"national",tr:"milli"});
hard.push({ eng:"natural",tr:"doğal"});
hard.push({ eng:"nautical",tr:"gemicilikle ilgili"});
hard.push({ eng:"naval",tr:"donanmayla ilgili"});
hard.push({ eng:"navigational",tr:"denizcilikle ilgili"});
hard.push({ eng:"neat",tr:"düzenli"});
hard.push({ eng:"necessary",tr:"gerekli"});
hard.push({ eng:"negative",tr:"olumsuz"});
hard.push({ eng:"nervous",tr:"sinirli"});
hard.push({ eng:"neutral",tr:"nötr"});
hard.push({ eng:"new",tr:"yeni"});
hard.push({ eng:"next",tr:"sonraki"});
hard.push({ eng:"nice",tr:"hoş"});
hard.push({ eng:"noisy",tr:"gürültülü"});
hard.push({ eng:"nominal",tr:"nominal"});
hard.push({ eng:"noncommissioned",tr:"assubay"});
hard.push({ eng:"normal",tr:"mormal"});
hard.push({ eng:"nuclear",tr:"nükleer"});
hard.push({ eng:"numeric",tr:"sayısal"});
hard.push({ eng:"numerous",tr:"çeşitli"});
hard.push({ eng:"obsolete",tr:"eskimiş"});
hard.push({ eng:"obvious",tr:"aşikar"});
hard.push({ eng:"occasional",tr:"arada bir olan"});
hard.push({ eng:"odd",tr:"garip"});
hard.push({ eng:"old",tr:"yaşlı/eski"});
hard.push({ eng:"open",tr:"açık"});
hard.push({ eng:"operational",tr:"kullanıma hazır"});
hard.push({ eng:"opposite",tr:"zıt"});
hard.push({ eng:"optimum",tr:"optimum"});
hard.push({ eng:"optional",tr:"tercihe bağlı"});
hard.push({ eng:"oral",tr:"sözel"});
hard.push({ eng:"ordinary",tr:"sıradan"});
hard.push({ eng:"organizational",tr:"örgütsel"});
hard.push({ eng:"original",tr:"orijinal"});
hard.push({ eng:"other",tr:"diğer"});
hard.push({ eng:"outside",tr:"dış"});
hard.push({ eng:"outstanding",tr:"göze çarpan"});
hard.push({ eng:"outward",tr:"dış"});
hard.push({ eng:"overhead",tr:"yukarıda"});
hard.push({ eng:"oversize",tr:"büyük boy"});
hard.push({ eng:"own",tr:"kendisinin"});
hard.push({ eng:"pale",tr:"solgun"});
hard.push({ eng:"parallel",tr:"paralel"});
hard.push({ eng:"partial",tr:"bölümsel"});
hard.push({ eng:"particular",tr:"belirli"});
hard.push({ eng:"passive",tr:"pasif"});
hard.push({ eng:"past",tr:"geçmiş"});
hard.push({ eng:"peculiar",tr:"acayip"});
hard.push({ eng:"periodic",tr:"periyodik"});
hard.push({ eng:"peripheral",tr:"ikincil/önemsiz"});
hard.push({ eng:"permanent",tr:"sürekli"});
hard.push({ eng:"personal",tr:"kişisel"});
hard.push({ eng:"petty",tr:"önemsiz"});
hard.push({ eng:"phonetic",tr:"fonetik"});
hard.push({ eng:"physical",tr:"fiziksel"});
hard.push({ eng:"pictorial",tr:"resmedilmiş"});
hard.push({ eng:"plain",tr:"sade"});
hard.push({ eng:"planar",tr:"düzlemsel"});
hard.push({ eng:"plenty",tr:"bol miktar"});
hard.push({ eng:"poisonous",tr:"zehirli"});
hard.push({ eng:"polite",tr:"nazik"});
hard.push({ eng:"political",tr:"siyasi"});
hard.push({ eng:"poor",tr:"fakir/zavallı"});
hard.push({ eng:"portable",tr:"portatif"});
hard.push({ eng:"positive",tr:"olumlu"});
hard.push({ eng:"possible",tr:"mümkün"});
hard.push({ eng:"potential",tr:"potansiyel"});
hard.push({ eng:"powerful",tr:"güçlü"});
hard.push({ eng:"practical",tr:"pratik"});
hard.push({ eng:"precise",tr:"tam/kesin"});
hard.push({ eng:"predictable",tr:"tahmin edilebilir"});
hard.push({ eng:"preliminary",tr:"ilk/ön"});
hard.push({ eng:"pretty",tr:"hoş/çekici"});
hard.push({ eng:"preventive",tr:"önleyici"});
hard.push({ eng:"previous",tr:"önceki"});
hard.push({ eng:"primary",tr:"baş/temel"});
hard.push({ eng:"prior",tr:"önceki/öncelikli"});
hard.push({ eng:"private",tr:"özel"});
hard.push({ eng:"probable",tr:"muhtemel"});
hard.push({ eng:"productive",tr:"verimli"});
hard.push({ eng:"professional",tr:"profesyonel"});
hard.push({ eng:"programmable",tr:"programlanabilir"});
hard.push({ eng:"prompt",tr:"seri/çabuk"});
hard.push({ eng:"proper",tr:"münasip"});
hard.push({ eng:"protective",tr:"koruyucu"});
hard.push({ eng:"proximate",tr:"en yakın"});
hard.push({ eng:"punitive",tr:"acımasız/sert"});
hard.push({ eng:"pure",tr:"katıksız"});
hard.push({ eng:"purple",tr:"mor"});
hard.push({ eng:"quantitative",tr:"nicel"});
hard.push({ eng:"quick",tr:"hızlı"});
hard.push({ eng:"radioactive",tr:"radyoaktif"});
hard.push({ eng:"random",tr:"düzensiz"});
hard.push({ eng:"rapid",tr:"hızlı"});
hard.push({ eng:"raw",tr:"ham/çiğ"});
hard.push({ eng:"ready",tr:"hazır"});
hard.push({ eng:"real",tr:"gerçek"});
hard.push({ eng:"reasonable",tr:"makul/mantıklı"});
hard.push({ eng:"rectangular",tr:"dikdörtgen biçiminde "});
hard.push({ eng:"red",tr:"kırmızı"});
hard.push({ eng:"redundant",tr:"gereksiz"});
hard.push({ eng:"refreshing",tr:"canlandırıcı"});
hard.push({ eng:"regional",tr:"bölgesel"});
hard.push({ eng:"regular",tr:"düzenli"});
hard.push({ eng:"relative",tr:"göreli/oranlı"});
hard.push({ eng:"reliable",tr:"güvenilir"});
hard.push({ eng:"remote",tr:"uzak"});
hard.push({ eng:"respective",tr:"kendi/kişisel"});
hard.push({ eng:"responsible",tr:"sorumlu"});
hard.push({ eng:"retail",tr:"perakende"});
hard.push({ eng:"reusable",tr:"tekrar kullanılabilir"});
hard.push({ eng:"rich",tr:"zengin"});
hard.push({ eng:"right",tr:"doğru/sağ"});
hard.push({ eng:"rigid",tr:"sert/eğilmez"});
hard.push({ eng:"ripe",tr:"olgun"});
hard.push({ eng:"rough",tr:"pürüzlü/kaba"});
hard.push({ eng:"sad",tr:"üzgün"});
hard.push({ eng:"safe",tr:"güvenli"});
hard.push({ eng:"same",tr:"aynı"});
hard.push({ eng:"satisfactory",tr:"hoşnut edici"});
hard.push({ eng:"schematic",tr:"şematik"});
hard.push({ eng:"secondary",tr:"ikincil"});
hard.push({ eng:"secure",tr:"güvenli"});
hard.push({ eng:"senior",tr:"kıdemli"});
hard.push({ eng:"sensitive",tr:"hassas"});
hard.push({ eng:"separate",tr:"ayrı"});
hard.push({ eng:"sequential",tr:"ardışık"});
hard.push({ eng:"serious",tr:"ciddi"});
hard.push({ eng:"serviceable",tr:"dayanıklı/kullanışlı"});
hard.push({ eng:"seventh",tr:"yedinci"});
hard.push({ eng:"several",tr:"çeşitli"});
hard.push({ eng:"severe",tr:"sert/şiddetli"});
hard.push({ eng:"shady",tr:"gölgeli"});
hard.push({ eng:"shallow",tr:"sığ/yüzeysel"});
hard.push({ eng:"sharp",tr:"keskin"});
hard.push({ eng:"shy",tr:"utangaç"});
hard.push({ eng:"shiny",tr:"parlak"});
hard.push({ eng:"shipboard",tr:"gemide"});
hard.push({ eng:"shipshape",tr:"düzgün/muntazam"});
hard.push({ eng:"short",tr:"kısa"});
hard.push({ eng:"sick",tr:"hasta"});
hard.push({ eng:"significant",tr:"önemli"});
hard.push({ eng:"silent",tr:"sessiz"});
hard.push({ eng:"similar",tr:"benzer"});
hard.push({ eng:"simple",tr:"basit"});
hard.push({ eng:"simultaneous",tr:"eş zamanlı"});
hard.push({ eng:"single",tr:"tek/bekar"});
hard.push({ eng:"sixth",tr:"altıncı"});
hard.push({ eng:"slack",tr:"gevşek"});
hard.push({ eng:"slight",tr:"ince/narin"});
hard.push({ eng:"slippery",tr:"kaygan"});
hard.push({ eng:"small",tr:"küçük"});
hard.push({ eng:"smart",tr:"zarif/gösterişli"});
hard.push({ eng:"smooth",tr:"düz/akıcı"});
hard.push({ eng:"snug",tr:"rahat/tam oturan"});
hard.push({ eng:"social",tr:"sosyal"});
hard.push({ eng:"soft",tr:"yumuşak"});
hard.push({ eng:"solar",tr:"güneşle ilgili"});
hard.push({ eng:"solid",tr:"katı"});
hard.push({ eng:"some",tr:"biraz"});
hard.push({ eng:"sour",tr:"ekşi"});
hard.push({ eng:"special",tr:"özel"});
hard.push({ eng:"specific",tr:"belirli"});
hard.push({ eng:"splitting",tr:"şiddetli"});
hard.push({ eng:"stable",tr:"sağlam/sürekli"});
hard.push({ eng:"standby",tr:"yedek"});
hard.push({ eng:"static",tr:"statik"});
hard.push({ eng:"stationary",tr:"sabit"});
hard.push({ eng:"steady",tr:"sabit/sağlam"});
hard.push({ eng:"steep",tr:"dik/sarp"});
hard.push({ eng:"sterile",tr:"steril"});
hard.push({ eng:"sticky",tr:"yapışkan"});
hard.push({ eng:"stiff",tr:"katı/sert"});
hard.push({ eng:"still",tr:"durgun"});
hard.push({ eng:"straight",tr:"dümdüz"});
hard.push({ eng:"strange",tr:"acayip/tuhaf"});
hard.push({ eng:"stranger",tr:"yabancı"});
hard.push({ eng:"strategic",tr:"stratejik"});
hard.push({ eng:"strict",tr:"katı/sağlam"});
hard.push({ eng:"strong",tr:"güçlü"});
hard.push({ eng:"structural",tr:"yapısal"});
hard.push({ eng:"subsequent",tr:"sonradan gelen"});
hard.push({ eng:"substantial",tr:"dayanıklı/önemli"});
hard.push({ eng:"successful",tr:"başarılı"});
hard.push({ eng:"successive",tr:"ardıl"});
hard.push({ eng:"such",tr:"öylesine"});
hard.push({ eng:"sudden",tr:"ani"});
hard.push({ eng:"sufficient",tr:"yeterli"});
hard.push({ eng:"suitable",tr:"uygun"});
hard.push({ eng:"sunny",tr:"güneşli"});
hard.push({ eng:"superior",tr:"yüksek/üstün"});
hard.push({ eng:"superlative",tr:"en iyi/üstün"});
hard.push({ eng:"supplementary",tr:"ilave/ek"});
hard.push({ eng:"sure",tr:"kesin"});
hard.push({ eng:"sweet",tr:"tatlı"});
hard.push({ eng:"swift",tr:"atik/tez"});
hard.push({ eng:"swollen",tr:"şiş/kabarık"});
hard.push({ eng:"symbolic",tr:"sembolik"});
hard.push({ eng:"synthetic",tr:"sentetik"});
hard.push({ eng:"tactical",tr:"taktiksel"});
hard.push({ eng:"tall",tr:"uzun"});
hard.push({ eng:"taut",tr:"gergin"});
hard.push({ eng:"technical",tr:"teknik"});
hard.push({ eng:"temporary",tr:"geçici"});
hard.push({ eng:"tentative",tr:"öneri niteliğinde"});
hard.push({ eng:"terminal",tr:"ölümcül"});
hard.push({ eng:"thermal",tr:"termal"});
hard.push({ eng:"thick",tr:"kalın"});
hard.push({ eng:"third",tr:"üçüncü"});
hard.push({ eng:"thirsty",tr:"susamış"});
hard.push({ eng:"thorough",tr:"tam/eksiksiz"});
hard.push({ eng:"tight",tr:"dar"});
hard.push({ eng:"tiny",tr:"küçük/ufak"});
hard.push({ eng:"toxic",tr:"zehirli"});
hard.push({ eng:"transient",tr:"geçici"});
hard.push({ eng:"transparent",tr:"transparan"});
hard.push({ eng:"transverse",tr:"enine/çaprazlama"});
hard.push({ eng:"tropical",tr:"tropikal"});
hard.push({ eng:"true",tr:"doğru"});
hard.push({ eng:"turbulent",tr:"vahşi/sert"});
hard.push({ eng:"typical",tr:"tipik"});
hard.push({ eng:"undersea",tr:"denizaltı"});
hard.push({ eng:"undersigned",tr:"aşağıda imzası bulunan"});
hard.push({ eng:"underwater",tr:"su altı"});
hard.push({ eng:"unique",tr:"eşsiz"});
hard.push({ eng:"universal",tr:"evrensel"});
hard.push({ eng:"upper",tr:"üstteki"});
hard.push({ eng:"uppermost",tr:"başlıca"});
hard.push({ eng:"urgent",tr:"acil"});
hard.push({ eng:"useful",tr:"faydalı"});
hard.push({ eng:"usual",tr:"olağan"});
hard.push({ eng:"valid",tr:"geçerli"});
hard.push({ eng:"valuable",tr:"değerli"});
hard.push({ eng:"variable",tr:"değişken"});
hard.push({ eng:"various",tr:"çeşitli"});
hard.push({ eng:"vertical",tr:"dikey"});
hard.push({ eng:"viable",tr:"uygulanabilir"});
hard.push({ eng:"violent",tr:"şiddetli"});
hard.push({ eng:"virtual",tr:"gerçek/asıl"});
hard.push({ eng:"visible",tr:"görülebilir"});
hard.push({ eng:"visual",tr:"görsel"});
hard.push({ eng:"vital",tr:"önemli/hayati"});
hard.push({ eng:"void",tr:"hükümsüz/geçersiz"});
hard.push({ eng:"volatile",tr:"değişken/dönek"});
hard.push({ eng:"wanton",tr:"değişken/kontrolsüz"});
hard.push({ eng:"warm",tr:"ılık"});
hard.push({ eng:"waterproof",tr:"su geçirmez"});
hard.push({ eng:"watertight",tr:"suya dayanıklı"});
hard.push({ eng:"weak",tr:"zayıf"});
hard.push({ eng:"weary",tr:"yorgun/usanmış"});
hard.push({ eng:"wet",tr:"ıslak"});
hard.push({ eng:"white",tr:"beyaz"});
hard.push({ eng:"whole",tr:"tüm"});
hard.push({ eng:"wide",tr:"geniş"});
hard.push({ eng:"willful",tr:"inatçı"});
hard.push({ eng:"wise",tr:"akıllı/mantıklı"});
hard.push({ eng:"wooden",tr:"tahta/ahşap"});
hard.push({ eng:"woolen",tr:"yün"});
hard.push({ eng:"wrong",tr:"yanlış"});
hard.push({ eng:"wrongful",tr:"haksız"});
hard.push({ eng:"yellow",tr:"sarı"});
hard.push({ eng:"yesterday",tr:"dün"});
hard.push({ eng:"young",tr:"genç"});
hard.push({ eng:"harmless",tr:"zararsız"});
hard.push({ eng:"inactive",tr:"hareketsiz/pasif"});
hard.push({ eng:"incomplete",tr:"tamamlanmamış"});
hard.push({ eng:"incorrect",tr:"yanlış"});
hard.push({ eng:"indirect",tr:"dolaylı"});
hard.push({ eng:"invalid",tr:"geçersiz"});
hard.push({ eng:"nonavailable",tr:"namevcut"});
hard.push({ eng:"nonproductive",tr:"üretken olmayan"});
hard.push({ eng:"unauthorized",tr:"yetkisiz"});
hard.push({ eng:"undesired",tr:"istenmeyen"});
hard.push({ eng:"unfinished",tr:"bitmemiş"});
hard.push({ eng:"unimportant",tr:"önemsiz"});
hard.push({ eng:"unknown",tr:"bilinmeyen"});
hard.push({ eng:"unsafe",tr:"emniyetsiz"});
hard.push({ eng:"unsuccessful",tr:"başarısız"});
hard.push({ eng:"unused",tr:"kullanılmayan"});
hard.push({ eng:"unusual",tr:"olağan dışı"});
hard.push({ eng:"unwanted",tr:"istenmeyen"});
hard.push({ eng:"useless",tr:"faydasız "});
