var basic=[];
var medium = [];
var hard = [];
basic.push({ eng:"actually",tr:" gerçekte"});
basic.push({ eng:"amazingly",tr:"şaşırtıcı bir şekilde"});
basic.push({ eng:"approximately",tr:" yaklaşık olarak"});
basic.push({ eng:"attractively",tr:" etkileyici bir şekilde"});
basic.push({ eng:"automatically",tr:"otomatikman"});
basic.push({ eng:"awfully",tr:" fena halde, korkunç bir şekilde"});
basic.push({ eng:"badly",tr:" fena halde"});
basic.push({ eng:"beautifully",tr:" güzel bir şekilde"});
basic.push({ eng:"bravely",tr:" cesaretle"});
basic.push({ eng:"briefly",tr:" kısaca"});
basic.push({ eng:"brightly",tr:" parlak bir şekilde, zekice"});
basic.push({ eng:"carelessly",tr:" dikkatsizce"});
basic.push({ eng:"certainly",tr:"kesinlikle, elbette"});
basic.push({ eng:"cheerfully",tr:" neşeyle, keyifle"});
basic.push({ eng:"clearly",tr:" açıkça"});
basic.push({ eng:"comfortably",tr:" rahatça"});
basic.push({ eng:"completely",tr:" tamamen"});
basic.push({ eng:"deeply",tr:" derinden,çok"});
basic.push({ eng:"differently",tr:" farklı bir şekilde"});
basic.push({ eng:"dishonestly",tr:" namussuzca"});
basic.push({ eng:"effectively",tr:" etkili olarak"});
basic.push({ eng:"enormously",tr:" aşırı derecede"});
basic.push({ eng:"equally",tr:" eşit olarak"});
basic.push({ eng:"exactly",tr:"tam olarak"});
basic.push({ eng:"familiarly",tr:" dostça"});
basic.push({ eng:"fluently",tr:" akıcı bir biçimde"});
basic.push({ eng:"formally",tr:" resmi olarak"});
basic.push({ eng:"fortunately",tr:" neyse ki,çok şükür, iyi ki"});
basic.push({ eng:"frequently",tr:" sık sık"});
basic.push({ eng:"generously",tr:" cömertçe"});
basic.push({ eng:"gently",tr:" nazikçe, yavaşça, tatlılıkla"});
basic.push({ eng:"greatly",tr:"oldukça, fazlaca, epeyce"});
basic.push({ eng:"heavily",tr:" ağır, yoğun bir şekilde"});
basic.push({ eng:"highly",tr:" hayli"});
basic.push({ eng:"hopefully",tr:"ümitle"});
basic.push({ eng:"intelligently",tr:" akıllıca"});
basic.push({ eng:"joyfully",tr:" neşeyle"});
basic.push({ eng:"lately",tr:" son zamanlarda, yakınlarda"});
basic.push({ eng:"lively",tr:" canlı, neşeli"});
basic.push({ eng:"luckily",tr:"şanslı şekilde"});
basic.push({ eng:"mainly",tr:"çoğunlukla"});
basic.push({ eng:"naturally",tr:" doğal olarak"});
basic.push({ eng:"nearly",tr:" neredeyse"});
basic.push({ eng:"nervously",tr:" sinirli olarak"});
basic.push({ eng:"patiently",tr:"sabırla"});
basic.push({ eng:"peacefully",tr:" huzurlu bir şekilde"});
basic.push({ eng:"perfectly ",tr:"mükemmel bir şekilde"});
basic.push({ eng:"pleasantly",tr:" hoş bir şekilde"});
basic.push({ eng:"potentially ",tr:"imkan dahilinde"});
basic.push({ eng:"practically ",tr:"hemen hemen"});
basic.push({ eng:"previously",tr:"önceden"});
basic.push({ eng:"privately",tr:"özel olarak"});
basic.push({ eng:"quickly",tr:"çabuk, acele bir şekilde"});
basic.push({ eng:"rapidly",tr:" hızlıca"});
basic.push({ eng:"regularly",tr:" düzenli olarak"});
basic.push({ eng:"reliably",tr:" güvenilir şekilde"});
basic.push({ eng:"remarkably",tr:" dikkate değer biçimde"});
basic.push({ eng:"safely",tr:" güvenli bir şekilde"});
basic.push({ eng:"seriously",tr:"ciddi bir şekilde"});
basic.push({ eng:"shortly",tr:" yakında, kısaca"});
basic.push({ eng:"shyly",tr:"ürkekçe"});
basic.push({ eng:"simply ",tr:"sadece"});
basic.push({ eng:"slowly",tr:" yavaşça"});
basic.push({ eng:"stupidly",tr:" ahmakça"});
basic.push({ eng:"surely",tr:" muhakkak"});
basic.push({ eng:"terribly ",tr:"korkunç, müthiş bir şekilde"});
basic.push({ eng:"tightly",tr:" sıkıca"});
basic.push({ eng:"truly",tr:" gerçekten"});
basic.push({ eng:"unusually",tr:" nadiren"});
basic.push({ eng:"wisely",tr:" akıllıca"});


medium.push({ eng:"absolutely",tr:" tamamen, kesinlikle"});
medium.push({ eng:"accidentally",tr:" kazara"});
medium.push({ eng:"accordingly",tr:" buna göre, bu bağlamda"});
medium.push({ eng:"actually ",tr:"gerçekte"});
medium.push({ eng:"adventurously",tr:" macera vari bir şekilde"});
medium.push({ eng:"agreeably",tr:" kabul edilir bir şekilde"});
medium.push({ eng:"amazingly ",tr:" şaşırtıcı bir şekilde"});
medium.push({ eng:"ambitiously",tr:" hırsla"});
medium.push({ eng:"amusingly",tr:"hoş bir şekilde"});
medium.push({ eng:"anxiously",tr:" endişe ile"});
medium.push({ eng:"apparently",tr:" görünüşe bakılırsa"});
medium.push({ eng:"appropriately",tr:" uygun bir şekilde"});
medium.push({ eng:"approximately",tr:" yaklaşık olarak"});
medium.push({ eng:"artificially",tr:" yapay, suni olarak"});
medium.push({ eng:"attractively",tr:" etkileyici bir şekilde"});
medium.push({ eng:"automatically",tr:"otomatikman"});
medium.push({ eng:"awfully",tr:" fena halde, korkunç bir şekilde"});
medium.push({ eng:"badly ",tr:"fena halde"});
medium.push({ eng:"barely",tr:" ancak, güçbela"});
medium.push({ eng:"beautifully",tr:" güzel bir şekilde"});
medium.push({ eng:"bravely ",tr:"cesaretle"});
medium.push({ eng:"briefly",tr:" kısaca"});
medium.push({ eng:"brightly",tr:" parlak bir şekilde, zekice"});
medium.push({ eng:"carelessly",tr:" dikkatsizce"});
medium.push({ eng:"casually",tr:" gayri resmi olarak"});
medium.push({ eng:"cautiously",tr:" dikkatli bir şekilde"});
medium.push({ eng:"certainly",tr:" kesinlikle, elbette"});
medium.push({ eng:"cheerfully",tr:" neşeyle, keyifle"});
medium.push({ eng:"clearly",tr:" açıkça"});
medium.push({ eng:"comfortably",tr:" rahatça"});
medium.push({ eng:"comparatively",tr:" nispeten, epeyce"});
medium.push({ eng:"completely",tr:" tamamen"});
medium.push({ eng:"consequently",tr:"netice olarak"});
medium.push({ eng:"constantly",tr:" sürekli olarak"});
medium.push({ eng:"conveniently",tr:" elverişli şekilde"});
medium.push({ eng:"cordially",tr:" samimiyetle"});
medium.push({ eng:"curiously",tr:"meraklı bir şekilde"});
medium.push({ eng:"currently",tr:" halen,şuanda"});
medium.push({ eng:"deadly",tr:"öldürücü bir şekilde, kesinlikle"});
medium.push({ eng:"decisively",tr:" kararlılıkla"});
medium.push({ eng:"deeply",tr:" derinden,çok"});
medium.push({ eng:"definitely ",tr:"kesinlikle"});
medium.push({ eng:"deliberately",tr:" kasten, bilebile"});
medium.push({ eng:"delicately",tr:" narin, hassas bir şekilde"});
medium.push({ eng:"desperately",tr:"ümitsizce, aşırı bir şekilde"});
medium.push({ eng:"differently",tr:" farklı bir şekilde"});
medium.push({ eng:"dishonestly",tr:" namussuzca"});
medium.push({ eng:"distastefully",tr:" tatsız şekilde, nahoş bir biçimde"});
medium.push({ eng:"doubtfully",tr:" kuşkulu bir şekilde"});
medium.push({ eng:"dramatically",tr:"çarpıcı olarak,önemli ölçüde"});
medium.push({ eng:"eagerly",tr:" şevkle, istekle"});
medium.push({ eng:"effectively",tr:" etkili olarak"});
medium.push({ eng:"elegantly",tr:" nezaketle"});
medium.push({ eng:"enormously",tr:" aşırı derecede"});
medium.push({ eng:"entirely",tr:" tamamen"});
medium.push({ eng:"equally",tr:" eşit olarak"});
medium.push({ eng:"essentially",tr:" esasen"});
medium.push({ eng:"eventually",tr:" nihayetinde, en sonunda"});
medium.push({ eng:"evidently",tr:" belli ki"});
medium.push({ eng:"exactly ",tr:"tam olarak"});
medium.push({ eng:"exhaustedly",tr:" tükenmiş, yorgun bir şekilde"});
medium.push({ eng:"exhaustively",tr:" etraflıca, kapsamlı bir şekilde"});
medium.push({ eng:"experimentally ",tr:"deneysel olarak"});
medium.push({ eng:"explicitly",tr:" açıkça"});
medium.push({ eng:"extensively",tr:" kapsamlı bir şekilde"});
medium.push({ eng:"extraordinarily",tr:"olağanüstü bir şekilde"});
medium.push({ eng:"extremely",tr:" aşırı derecede"});
medium.push({ eng:"faithfully ",tr:"sadakatle"});
medium.push({ eng:"familiarly ",tr:"dostça"});
medium.push({ eng:"fantastically",tr:" aşırı derecede"});
medium.push({ eng:"fluently",tr:" akıcı bir biçimde"});
medium.push({ eng:"formally ",tr:"resmi olarak"});
medium.push({ eng:"fortunately",tr:" neyse ki,çok şükür, iyi ki"});
medium.push({ eng:"frequently",tr:" sık sık"});
medium.push({ eng:"frightfully ",tr:"korkunç bir şekilde"});
medium.push({ eng:"fully ",tr:"tamamen"});
medium.push({ eng:"fundamentally ",tr:"esasen, esaslı bir şekilde"});
medium.push({ eng:"generously ",tr:"cömertçe"});
medium.push({ eng:"gently ",tr:"nazikçe, yavaşça, tatlılıkla"});
medium.push({ eng:"gradually ",tr:"giderek, git gide artarak"});
medium.push({ eng:"greatly",tr:"oldukça, fazlaca, epeyce"});
medium.push({ eng:"heavily ",tr:"ağır, yoğun bir şekilde"});
medium.push({ eng:"highly ",tr:"hayli"});
medium.push({ eng:"hopefully ",tr:" ümitle"});
medium.push({ eng:"hospitably ",tr:"misafirperverlikle"});
medium.push({ eng:"incorrectly ",tr:"yanlış olarak"});
medium.push({ eng:"increasingly ",tr:"giderek, gitgideartarak"});
medium.push({ eng:"indecently ",tr:"edepsizce, ahlaksızca"});
medium.push({ eng:"indecisively",tr:" kesin olmayarak"});
medium.push({ eng:"indefinitely ",tr:"süresiz olarak"});
medium.push({ eng:"independently ",tr:"bağımsız olarak"});
medium.push({ eng:"individually ",tr:"ayrı ayrı"});
medium.push({ eng:"intelligently ",tr:"akıllıca"});
medium.push({ eng:"intelligibly ",tr:"anlaşılır biçimde"});
medium.push({ eng:"intensely ",tr:"yoğun bir şekilde"});
medium.push({ eng:"joyfully",tr:" neşeyle"});
medium.push({ eng:"lately",tr:" son zamanlarda, yakınlarda"});
medium.push({ eng:"literally ",tr:"harfi harfine"});
medium.push({ eng:"lively (adj.) ",tr:"canlı, neşeli"});
medium.push({ eng:"luckily",tr:"şanslı şekilde"});
medium.push({ eng:"mainly ",tr:" çoğunlukla"});
medium.push({ eng:"masterly ",tr:"ustaca"});
medium.push({ eng:"naturally ",tr:"doğal olarak"});
medium.push({ eng:"nearly ",tr:"neredeyse"});
medium.push({ eng:"nervously",tr:" sinirli olarak"});
medium.push({ eng:"painfully",tr:"ıstırap vererek"});
medium.push({ eng:"partially ",tr:"kısmen"});
medium.push({ eng:"particularly",tr:"özellikle"});
medium.push({ eng:"patiently ",tr:"sabırla"});
medium.push({ eng:"peacefully ",tr:"huzurlu bir şekilde"});
medium.push({ eng:"perfectly ",tr:"mükemmel bir şekilde"});
medium.push({ eng:"plainly ",tr:"açıkça"});
medium.push({ eng:"pleasantly ",tr:"hoş bir şekilde"});
medium.push({ eng:"potentially",tr:" imkan dahilinde"});
medium.push({ eng:"practically ",tr:"hemen hemen"});
medium.push({ eng:"previously",tr:"önceden"});
medium.push({ eng:"privately ",tr:" özel olarak"});
medium.push({ eng:"prominently ",tr:"egemen, baskın bir şekilde"});
medium.push({ eng:"properly",tr:" uygun şekilde"});
medium.push({ eng:"publicly",tr:" alenen"});
medium.push({ eng:"purely ",tr:"sadece, yalnız"});
medium.push({ eng:"quickly",tr:"çabuk, acele bir şekilde"});
medium.push({ eng:"randomly ",tr:"rast gele"});
medium.push({ eng:"rapidly",tr:" hızlıca"});
medium.push({ eng:"readily ",tr:"hemence, isteyerek"});
medium.push({ eng:"reasonably ",tr:" oldukça"});
medium.push({ eng:"regularly",tr:" düzenli olarak"});
medium.push({ eng:"relatively ",tr:"nispeten"});
medium.push({ eng:"relentlessly",tr:" merhametsizce"});
medium.push({ eng:"reliably",tr:" güvenilir şekilde"});
medium.push({ eng:"remarkably ",tr:"dikkate değer biçimde"});
medium.push({ eng:"roughly ",tr:"kabaca"});
medium.push({ eng:"safely ",tr:"güvenli bir şekilde"});
medium.push({ eng:"satisfactorily",tr:" tatmin edici biçimde"});
medium.push({ eng:"securely",tr:" güvenle, kesin olarak"});
medium.push({ eng:"sensibly ",tr:"makul bir şekilde"});
medium.push({ eng:"sensitively",tr:" duyarlıca"});
medium.push({ eng:"seriously",tr:" ciddi bir şekilde"});
medium.push({ eng:"severely ",tr:"sert, ciddi bir sekilde"});
medium.push({ eng:"shortly",tr:" yakında, kısaca"});
medium.push({ eng:"shyly ",tr:" ürkekçe"});
medium.push({ eng:"simply ",tr:"sadece"});
medium.push({ eng:"simultaneously",tr:" eşzamanlı"});
medium.push({ eng:"skillfully ",tr:"becerikli bir biçimde"});
medium.push({ eng:"slightly ",tr:"hafifçe"});
medium.push({ eng:"slowly ",tr:"yavaşça"});
medium.push({ eng:"smoothly",tr:" sorunsuz olarak"});
medium.push({ eng:"sorrowfully",tr:" hazinbir şekilde"});
medium.push({ eng:"steadily ",tr:"düzenli bir şekilde"});
medium.push({ eng:"stupidly ",tr:"ahmakça"});
medium.push({ eng:"surely ",tr:"muhakkak"});
medium.push({ eng:"tactlessly ",tr:"patavatsızca"});
medium.push({ eng:"tenderly ",tr:" şefkatle"});
medium.push({ eng:"terribly ",tr:"korkunç, müthiş bir şekilde"});
medium.push({ eng:"thoroughly ",tr:"tamamen"});
medium.push({ eng:"tightly ",tr:"sıkıca"});
medium.push({ eng:"timidly",tr:" ürkekçe"});
medium.push({ eng:"tolerantly ",tr:"toleranslı bir şekilde"});
medium.push({ eng:"truly ",tr:"gerçekten"});
medium.push({ eng:"ultimately ",tr:"sonunda"});
medium.push({ eng:"unconsciously",tr:" bilinçsizce"});
medium.push({ eng:"undoubtedly ",tr:" şüphesiz"});
medium.push({ eng:"unexpectedly ",tr:"ansızın"});
medium.push({ eng:"unpleasantly ",tr:"nahoş bir şekilde"});
medium.push({ eng:"unusually ",tr:"nadiren"});
medium.push({ eng:"urgently",tr:" acilen"});
medium.push({ eng:"utterly ",tr:"tamamen"});
medium.push({ eng:"vaguely ",tr:"belirsizce"});
medium.push({ eng:"variably ",tr:"kararsız"});
medium.push({ eng:"virtually ",tr:"neredeyse, hemen hemen"});
medium.push({ eng:"vitally ",tr:"hayati olarak"});
medium.push({ eng:"voluntarily ",tr:"gönüllü bir şekilde"});
medium.push({ eng:"wastefully ",tr:"savurgan bir şekilde"});
medium.push({ eng:"widely ",tr:"yaygın olarak"});
medium.push({ eng:"willingly ",tr:"isteyerek"});
medium.push({ eng:"wisely ",tr:"akıllıca"});


hard.push({ eng:"abruptly ",tr:"birdenbire"});
hard.push({ eng:"absolutely",tr:"tamamen, kesinlikle"});
hard.push({ eng:"absurdly ",tr:"saçma bir şekilde"});
hard.push({ eng:"abundantly ",tr:"bol bol"});
hard.push({ eng:"accidentally ",tr:"kazara"});
hard.push({ eng:"accordingly",tr:" buna göre, bu bağlamda"});
hard.push({ eng:"accurately ",tr:"tam doğru bir şekilde"});
hard.push({ eng:"actually ",tr:"gerçekte"});
hard.push({ eng:"acutely ",tr:"ciddi şekilde"});
hard.push({ eng:"adamantly ",tr:"inatçı bir şekilde"});
hard.push({ eng:"adequately ",tr:"yeterince"});
hard.push({ eng:"admittedly",tr:" itiraf etmek gerekirse"});
hard.push({ eng:"adventurously ",tr:"macera vari bir şekilde"});
hard.push({ eng:"affectingly ",tr:"dokunaklı bir şekilde"});
hard.push({ eng:"agreeably",tr:" kabul edilir bir şekilde"});
hard.push({ eng:"amazingly ",tr:" şaşırtıcı bir şekilde"});
hard.push({ eng:"ambitiously",tr:" hırsla"});
hard.push({ eng:"amusingly ",tr:"hoş bir şekilde"});
hard.push({ eng:"anxiously ",tr:"endişe ile"});
hard.push({ eng:"apparently ",tr:"görünüşe bakılırsa"});
hard.push({ eng:"appropriately ",tr:"uygun bir şekilde"});
hard.push({ eng:"approximately ",tr:"yaklaşık olarak"});
hard.push({ eng:"aptly ",tr:"uygun bir şekilde"});
hard.push({ eng:"ardently ",tr:"gayretle, istekle"});
hard.push({ eng:"artfully ",tr:"ustaca"});
hard.push({ eng:"artificially ",tr:"yapay, suni olarak"});
hard.push({ eng:"attentively ",tr:"dikkatle"});
hard.push({ eng:"attractively ",tr:"etkileyici bir şekilde"});
hard.push({ eng:"automatically ",tr:" otomatikman"});
hard.push({ eng:"awfully ",tr:"fena halde, korkunç bir şekilde"});
hard.push({ eng:"awkwardly ",tr:"acemice"});
hard.push({ eng:"badly ",tr:"fena halde"});
hard.push({ eng:"barely ",tr:"ancak, güçbela"});
hard.push({ eng:"baselessly ",tr:"asılsızca"});
hard.push({ eng:"beautifully ",tr:"güzel bir şekilde"});
hard.push({ eng:"becomingly",tr:"uygun bir şekilde"});
hard.push({ eng:"beneficially ",tr:"faydalı bir şekilde"});
hard.push({ eng:"biennially ",tr:"iki yılda bir"});
hard.push({ eng:"bitterly ",tr:"feci bir şekilde"});
hard.push({ eng:"blatantly ",tr:"utanç verici şekilde, açıkça,çekinmeden"});
hard.push({ eng:"blissfully ",tr:"neşeyle"});
hard.push({ eng:"bluntly ",tr:"kesin bir dille"});
hard.push({ eng:"bravely ",tr:"cesaretle"});
hard.push({ eng:"briefly ",tr:"kısaca"});
hard.push({ eng:"brightly ",tr:"parlak bir şekilde, zekice"});
hard.push({ eng:"carelessly ",tr:"dikkatsizce"});
hard.push({ eng:"casually ",tr:"gayri resmi olarak"});
hard.push({ eng:"cautiously ",tr:"dikkatli bir şekilde"});
hard.push({ eng:"cavalierly ",tr:"cesaretle"});
hard.push({ eng:"certainly ",tr:"kesinlikle, elbette"});
hard.push({ eng:"cheerfully ",tr:"neşeyle, keyifle"});
hard.push({ eng:"charily ",tr:"ihtiyatla, istemeyerek"});
hard.push({ eng:"chiefly ",tr:"esas olarak"});
hard.push({ eng:"clearly ",tr:"açıkça"});
hard.push({ eng:"clumsily ",tr:" beceriksizce, acemice"});
hard.push({ eng:"coherently ",tr:"uyumlu bir şekilde"});
hard.push({ eng:"comfortably ",tr:"rahatça"});
hard.push({ eng:"comparatively ",tr:"nispeten, epeyce"});
hard.push({ eng:"competently ",tr:"ustaca"});
hard.push({ eng:"completely ",tr:"tamamen"});
hard.push({ eng:"conceivably ",tr:"belki"});
hard.push({ eng:"conclusively ",tr:"kesin olarak"});
hard.push({ eng:"consciously ",tr:"bilinçli olarak"});
hard.push({ eng:"consecutively ",tr:"arka arkaya"});
hard.push({ eng:"consequently ",tr:"netice olarak"});
hard.push({ eng:"considerably ",tr:" oldukça, epeyce"});
hard.push({ eng:"conjointly ",tr:"müştereken, birlikte"});
hard.push({ eng:"considerately ",tr:"düşünceli bir şekilde"});
hard.push({ eng:"consistently ",tr:"tutarlı bir şekilde"});
hard.push({ eng:"constantly ",tr:"sürekli olarak"});
hard.push({ eng:"conveniently ",tr:"elverişli şekilde"});
hard.push({ eng:"convincingly ",tr:"iknaedicibir şekilde"});
hard.push({ eng:"cordially ",tr:"samimiyetle"});
hard.push({ eng:"crudely ",tr:"kabaca"});
hard.push({ eng:"curiously ",tr:"meraklı bir şekilde"});
hard.push({ eng:"currently ",tr:"halen,şuanda"});
hard.push({ eng:"daringly ",tr:"cesurca"});
hard.push({ eng:"deadly ",tr:" öldürücü bir şekilde, kesinlikle"});
hard.push({ eng:"decidedly ",tr:"kesinlikle"});
hard.push({ eng:"decisively ",tr:"kararlılıkla"});
hard.push({ eng:"deeply ",tr:"derinden,çok"});
hard.push({ eng:"defectively ",tr:"kusurlu olarak"});
hard.push({ eng:"deficiently ",tr:"yetersizce"});
hard.push({ eng:"definitely ",tr:"kesinlikle"});
hard.push({ eng:"deliberately ",tr:"kasten, bilebile"});
hard.push({ eng:"delicately ",tr:"narin, hassas bir şekilde"});
hard.push({ eng:"densely ",tr:"yoğun bir şekilde"});
hard.push({ eng:"dependently ",tr:"eli kolu bağlı olarak"});
hard.push({ eng:"depressingly ",tr:"üzerek"});
hard.push({ eng:"desirably ",tr:"arzu edilirbir şekilde"});
hard.push({ eng:"desperately ",tr:" ümitsizce, aşırı bir şekilde"});
hard.push({ eng:"differently ",tr:"farklı bir şekilde"});
hard.push({ eng:"diminishingly ",tr:"eksilerek"});
hard.push({ eng:"disgustingly ",tr:"iğrenç bir şekilde"});
hard.push({ eng:"dishonestly",tr:" namussuzca"});
hard.push({ eng:"distastefully ",tr:"tatsız şekilde, nahoş bir biçimde"});
hard.push({ eng:"diversely ",tr:"farklı bir şekilde"});
hard.push({ eng:"doubtfully ",tr:"kuşkulu bir şekilde"});
hard.push({ eng:"dramatically ",tr:" çarpıcı olarak,önemli ölçüde"});
hard.push({ eng:"drowsily",tr:" uykulu bir şekilde"});
hard.push({ eng:"dubiously ",tr:" şüpheyle"});
hard.push({ eng:"eagerly ",tr:" şevkle, istekle"});
hard.push({ eng:"earnestly ",tr:"ciddi, samimi bir şekilde"});
hard.push({ eng:"effectively ",tr:"etkili olarak"});
hard.push({ eng:"effortlessly",tr:" kolayca"});
hard.push({ eng:"elaborately",tr:" ayrıntılı olarak"});
hard.push({ eng:"elegantly",tr:" nezaketle"});
hard.push({ eng:"embarrassingly ",tr:"utanç verici bir şekilde"});
hard.push({ eng:"endearingly ",tr:"sevimlice"});
hard.push({ eng:"enormously",tr:" aşırı derecede"});
hard.push({ eng:"enthusiastically",tr:" gayretli, hevesli bir şekilde"});
hard.push({ eng:"entirely ",tr:"tamamen"});
hard.push({ eng:"equally ",tr:"eşit olarak"});
hard.push({ eng:"essentially",tr:" esasen"});
hard.push({ eng:"eternally ",tr:"sürekli"});
hard.push({ eng:"eventually",tr:" nihayetinde, en sonunda"});
hard.push({ eng:"evidently",tr:" belli ki"});
hard.push({ eng:"exactly ",tr:"tam olarak"});
hard.push({ eng:"exceedingly aşırı bir şekilde"});
hard.push({ eng:"excellently ",tr:"mükemmel bir şekilde"});
hard.push({ eng:"exceptionally ",tr:" olağan üstü bir şekilde"});
hard.push({ eng:"excessively",tr:" aşırı derecede"});
hard.push({ eng:"exclusively ",tr:" özellikle, sadece"});
hard.push({ eng:"exhaustedly ",tr:"tükenmiş, yorgun bir şekilde"});
hard.push({ eng:"exhaustively ",tr:"etraflıca, kapsamlı bir şekilde"});
hard.push({ eng:"experimentally ",tr:"deneysel olarak"});
hard.push({ eng:"explicitly ",tr:"açıkça"});
hard.push({ eng:"extensively",tr:" kapsamlı bir şekilde"});
hard.push({ eng:"extraordinarily ",tr:" olağanüstü bir şekilde"});
hard.push({ eng:"extravagantly ",tr:"müsrifçe"});
hard.push({ eng:"extremely ",tr:"aşırı derecede"});
hard.push({ eng:"faithfully ",tr:"sadakatle"});
hard.push({ eng:"familiarly ",tr:"dostça"});
hard.push({ eng:"fantastically ",tr:"aşırı derecede"});
hard.push({ eng:"fatally ",tr:" öldürücü biçimde, ciddi bir biçimde"});
hard.push({ eng:"faultlessly ",tr:"kusursuz bir şekilde"});
hard.push({ eng:"favourably ",tr:"destekleyerek,olumlu görerek"});
hard.push({ eng:"feverishly ",tr:"heyecanlı, ateşli bir şekilde"});
hard.push({ eng:"fiercely ",tr:"kızgın, acımasız bir şekilde"});
hard.push({ eng:"flatly ",tr:" düpedüz, açıkça"});
hard.push({ eng:"fluently ",tr:"akıcı bir biçimde"});
hard.push({ eng:"formally ",tr:"resmi olarak"});
hard.push({ eng:"fortunately ",tr:"neyse ki,çok şükür, iyi ki"});
hard.push({ eng:"frankly",tr:" dürüst olmak gerekirse"});
hard.push({ eng:"frequently ",tr:"sık sık"});
hard.push({ eng:"frightfully ",tr:"korkunç bir şekilde"});
hard.push({ eng:"fully ",tr:"tamamen"});
hard.push({ eng:"fundamentally ",tr:"esasen, esaslı bir şekilde"});
hard.push({ eng:"generously",tr:" cömertçe"});
hard.push({ eng:"gently ",tr:"nazikçe, yavaşça, tatlılıkla"});
hard.push({ eng:"gradually ",tr:"giderek, git gide artarak"});
hard.push({ eng:"greatly ",tr:" oldukça, fazlaca, epeyce"});
hard.push({ eng:"half-heartedly",tr:" isteksizce"});
hard.push({ eng:"hardly ",tr:"hemen hemen hiç, zar zor"});
hard.push({ eng:"harshly ",tr:"sertçe, kaba bir şekilde"});
hard.push({ eng:"hastily ",tr:"aceleci bir şekilde"});
hard.push({ eng:"heavily ",tr:"ağır, yoğun bir şekilde"});
hard.push({ eng:"hesitantly ",tr:"tereddütlü bir şekilde"});
hard.push({ eng:"highly ",tr:"hayli"});
hard.push({ eng:"hopefully ",tr:" ümitle"});
hard.push({ eng:"hospitably ",tr:"misafirperverlikle"});
hard.push({ eng:"humorously ",tr:"espirilibir şekilde"});
hard.push({ eng:"immensely ",tr:"fazlasıyla, gayet"});
hard.push({ eng:"immorally ",tr:"ahlaksızca"});
hard.push({ eng:"impeccably ",tr:"hatasız olarak"});
hard.push({ eng:"impressively ",tr:"etkileyici bir şekilde"});
hard.push({ eng:"incautiously ",tr:"dikkatsizce"});
hard.push({ eng:"incessantly ",tr:"sürekli olarak"});
hard.push({ eng:"incompetently ",tr:"beceriksizce, acemice"});
hard.push({ eng:"inconsiderately",tr:"düşüncesizce"});
hard.push({ eng:"incorrectly ",tr:"yanlış olarak"});
hard.push({ eng:"increasingly",tr:" giderek, gitgideartarak"});
hard.push({ eng:"indecently ",tr:"edepsizce, ahlaksızca"});
hard.push({ eng:"indecisively",tr:" kesin olmayarak"});
hard.push({ eng:"indefinitely ",tr:"süresiz olarak"});
hard.push({ eng:"independently ",tr:"bağımsız olarak"});
hard.push({ eng:"indifferently ",tr:"ilgisizce"});
hard.push({ eng:"indisputably ",tr:"tartışmasız bir şekilde"});
hard.push({ eng:"individually ",tr:"ayrı ayrı"});
hard.push({ eng:"inevitably",tr:" kaçınılmaz biçimde"});
hard.push({ eng:"infectiously",tr:" bulaşıcı olarak"});
hard.push({ eng:"inferentially ",tr:"imalı bir şekilde"});
hard.push({ eng:"inherently ",tr:"doğal olarak"});
hard.push({ eng:"initially ",tr:"başlangıçta"});
hard.push({ eng:"intelligently ",tr:"akıllıca"});
hard.push({ eng:"intelligibly ",tr:"anlaşılır biçimde"});
hard.push({ eng:"intensely ",tr:"yoğun bir şekilde"});
hard.push({ eng:"intentionally ",tr:"bilebile, kasıtlı olarak"});
hard.push({ eng:"invariably ",tr:"sürekli olarak, hiç şaşmadan"});
hard.push({ eng:"inwardly ",tr:"içeride"});
hard.push({ eng:"joyfully ",tr:"neşeyle"});
hard.push({ eng:"lately",tr:" son zamanlarda, yakınlarda"});
hard.push({ eng:"literally",tr:" harfi harfine"});
hard.push({ eng:"lively (adj.) ",tr:"canlı, neşeli"});
hard.push({ eng:"luckily ",tr:" şanslı şekilde"});
hard.push({ eng:"mainly ",tr:" çoğunlukla"});
hard.push({ eng:"masterly ",tr:"ustaca"});
hard.push({ eng:"mercilessly ",tr:"acımasızca"});
hard.push({ eng:"merely ",tr:"sadece"});
hard.push({ eng:"meticulously ",tr:"kılı kırk yararak"});
hard.push({ eng:"mildly ",tr:" ılımlı bir şekilde"});
hard.push({ eng:"miraculously ",tr:"mucize eseri"});
hard.push({ eng:"moderately ",tr:" ılımlı bir şekilde"});
hard.push({ eng:"mournfully ",tr:"kederli bir şekilde"});
hard.push({ eng:"mourningly ",tr:"kederlice"});
hard.push({ eng:"mutually ",tr:"karşılıklı olarak"});
hard.push({ eng:"naturally ",tr:"doğal olarak"});
hard.push({ eng:"nearly ",tr:"neredeyse"});
hard.push({ eng:"nervously ",tr:"sinirli olarak"});
hard.push({ eng:"notably ",tr:" özellikle"});
hard.push({ eng:"obscurely",tr:" anlaşılmayacak şekilde"});
hard.push({ eng:"outwardly ",tr:"dışa dönük bir şekilde"});
hard.push({ eng:"painfully ",tr:" ıstırap vererek"});
hard.push({ eng:"partially ",tr:"kısmen"});
hard.push({ eng:"particularly",tr:"özellikle"});
hard.push({ eng:"patiently",tr:" sabırla"});
hard.push({ eng:"peacefully ",tr:"huzurlu bir şekilde"});
hard.push({ eng:"peculiarly ",tr:"acayip şekilde"});
hard.push({ eng:"perfectly ",tr:"mükemmel bir şekilde"});
hard.push({ eng:"perpetually ",tr:"daima"});
hard.push({ eng:"persistently ",tr:"inatla"});
hard.push({ eng:"placidly ",tr:"nazikçe"});
hard.push({ eng:"plainly ",tr:"açıkça"});
hard.push({ eng:"pleadingly ",tr:"yalvararak"});
hard.push({ eng:"pleasantly ",tr:"hoş bir şekilde"});
hard.push({ eng:"potentially ",tr:"imkan dahilinde"});
hard.push({ eng:"practically ",tr:"hemen hemen"});
hard.push({ eng:"precisely ",tr:"tam olarak"});
hard.push({ eng:"preferably ",tr:"tercihen"});
hard.push({ eng:"presumably ",tr:"muhtemelen"});
hard.push({ eng:"previously",tr:"önceden"});
hard.push({ eng:"privately",tr:"özel olarak"});
hard.push({ eng:"profoundly ",tr:"derinden,çok"});
hard.push({ eng:"progressively",tr:" aşamalı olarak"});
hard.push({ eng:"prominently ",tr:"egemen, baskın bir şekilde"});
hard.push({ eng:"properly ",tr:"uygun şekilde"});
hard.push({ eng:"proportionally ",tr:" orantılı olarak"});
hard.push({ eng:"publicly ",tr:"alenen"});
hard.push({ eng:"purely",tr:" sadece, yalnız"});
hard.push({ eng:"quickly ",tr:" çabuk, acele bir şekilde"});
hard.push({ eng:"randomly ",tr:"rast gele"});
hard.push({ eng:"rapidly",tr:" hızlıca"});
hard.push({ eng:"readily ",tr:"hemence, isteyerek"});
hard.push({ eng:"reasonably ",tr:" oldukça"});
hard.push({ eng:"recklessly ",tr:"dikkatsizce, pervasızca"});
hard.push({ eng:"regularly ",tr:"düzenli olarak"});
hard.push({ eng:"relatively ",tr:"nispeten"});
hard.push({ eng:"relentlessly ",tr:"merhametsizce"});
hard.push({ eng:"reliably ",tr:"güvenilir şekilde"});
hard.push({ eng:"reluctantly ",tr:"gönülsüzce"});
hard.push({ eng:"remarkably ",tr:"dikkate değer biçimde"});
hard.push({ eng:"resolutely ",tr:"azimle"});
hard.push({ eng:"respectively ",tr:"sırası ile"});
hard.push({ eng:"restrictedly ",tr:"sınırlı bir şekilde"});
hard.push({ eng:"roughly ",tr:"kabaca"});
hard.push({ eng:"safely ",tr:"güvenli bir şekilde"});
hard.push({ eng:"satisfactorily ",tr:"tatmin edici biçimde"});
hard.push({ eng:"securely ",tr:"güvenle, kesin olarak"});
hard.push({ eng:"sensibly ",tr:"makul bir şekilde"});
hard.push({ eng:"sensitively ",tr:"duyarlıca"});
hard.push({ eng:"sentimentally ",tr:"duygulu bir şekilde"});
hard.push({ eng:"seriously ",tr:"ciddi bir şekilde"});
hard.push({ eng:"severely ",tr:"sert, ciddi bir sekilde"});
hard.push({ eng:"shortly ",tr:"yakında, kısaca"});
hard.push({ eng:"shyly ",tr:" ürkekçe"});
hard.push({ eng:"simply ",tr:"sadece"});
hard.push({ eng:"simultaneously ",tr:"eşzamanlı"});
hard.push({ eng:"skillfully ",tr:"becerikli bir biçimde"});
hard.push({ eng:"slightly ",tr:"hafifçe"});
hard.push({ eng:"slowly ",tr:"yavaşça"});
hard.push({ eng:"slyly ",tr:"sinsice"});
hard.push({ eng:"smoothly ",tr:"sorunsuz olarak"});
hard.push({ eng:"solely ",tr:"sadece"});
hard.push({ eng:"sorrowfully ",tr:"hazinbir şekilde"});
hard.push({ eng:"sparsely ",tr:"seyrek olarak"});
hard.push({ eng:"spontaneously ",tr:"kendiliğinden"});
hard.push({ eng:"steadily ",tr:"düzenli bir şekilde"});
hard.push({ eng:"stupidly ",tr:"ahmakça"});
hard.push({ eng:"substantially ",tr:" önemli ölçüde"});
hard.push({ eng:"successively ",tr:"arka arkaya"});
hard.push({ eng:"succinctly ",tr:"kısaca"});
hard.push({ eng:"sufficiently ",tr:"yeterlibir şekilde"});
hard.push({ eng:"suitably ",tr:"uygun şekilde"});
hard.push({ eng:"superficially ",tr:"yüzeysel olarak"});
hard.push({ eng:"surely ",tr:"muhakkak"});
hard.push({ eng:"tactlessly ",tr:"patavatsızca"});
hard.push({ eng:"tenderly ",tr:" şefkatle"});
hard.push({ eng:"terribly ",tr:"korkunç, müthiş bir şekilde"});
hard.push({ eng:"thoroughly ",tr:"tamamen"});
hard.push({ eng:"thoughtlessly ",tr:"düşüncesizce"});
hard.push({ eng:"tightly ",tr:"sıkıca"});
hard.push({ eng:"timidly",tr:"ürkekçe"});
hard.push({ eng:"tolerantly ",tr:"toleranslı bir şekilde"});
hard.push({ eng:"tremendously ",tr:"aşırı bir şekilde"});
hard.push({ eng:"truly ",tr:"gerçekten"});
hard.push({ eng:"ultimately ",tr:"sonunda"});
hard.push({ eng:"unconsciously ",tr:"bilinçsizce"});
hard.push({ eng:"undeniably ",tr:"inkar edilmez bir şekilde"});
hard.push({ eng:"undoubtedly ",tr:" şüphesiz"});
hard.push({ eng:"unexpectedly ",tr:"ansızın"});
hard.push({ eng:"unpleasantly ",tr:"nahoş bir şekilde"});
hard.push({ eng:"unusually ",tr:"nadiren"});
hard.push({ eng:"urgently",tr:" acilen"});
hard.push({ eng:"utterly ",tr:"tamamen"});
hard.push({ eng:"vaguely ",tr:"belirsizce"});
hard.push({ eng:"variably ",tr:"kararsız"});
hard.push({ eng:"vehemently ",tr:" şiddetle"});
hard.push({ eng:"vigorously ",tr:"gayretli, yorucu bir şekilde"});
hard.push({ eng:"virtually ",tr:"neredeyse, hemen hemen"});
hard.push({ eng:"vitally ",tr:"hayati olarak"});
hard.push({ eng:"voluntarily ",tr:"gönüllü bir şekilde"});
hard.push({ eng:"wastefully ",tr:"savurgan bir şekilde"});
hard.push({ eng:"widely",tr:" yaygın olarak"});
hard.push({ eng:"willingly",tr:" isteyerek"});
hard.push({ eng:"wisely ",tr:"akıllıca"});
